// domande.js — database completo estratto dai PDF
// Formato: { id, argomento, domanda, risposta }
// Fonte: "Terapia Medica" dispensa Enrica Piazza (UNISR)
// Aggiornato: domande aggiunte e ID rinumerati progressivamente

const domande = [

  // --- 1. FEBBRE E ANTIPIRETICI ---------------------------------------
  {id: 1, argomento: "Febbre e antipiretici", domanda: "Quando NON si tratta la febbre?", risposta: "Quando è ben tollerata e utile come difesa: la febbre non va abbattuta di routine, ma solo se mal tollerata, molto elevata o nei soggetti fragili (cardiopatici, gravide, bambini con storia di convulsioni)."},
  {id: 2, argomento: "Febbre e antipiretici", domanda: "Indica 2 antipiretici con posologia.", risposta: "Paracetamolo 500-1000 mg ogni 6-8 h (max 3-4 g/die); ibuprofene 200-400 mg ogni 6-8 h."},
  {id: 3, argomento: "Febbre e antipiretici", domanda: "Bambino con febbre: cosa è meglio NON dare e perché?", risposta: "L'acido acetilsalicilico (aspirina), per il rischio di sindrome di Reye (encefalopatia + degenerazione epatica)."},
  {id: 4, argomento: "Febbre e antipiretici", domanda: "Bambino febbrile a 39°C con tosse/sinusite che diventa confuso e irritabile dopo un farmaco prescritto: quale farmaco?", risposta: "Aspirina → sindrome di Reye."},
  {id: 5, argomento: "Febbre e antipiretici", domanda: "Metabolita attivo della fenacetina ed esempio di posologia.", risposta: "Paracetamolo (acetaminofene); 500-1000 mg ogni 6-8 h, max 3-4 g/die."},
  {id: 6, argomento: "Febbre e antipiretici", domanda: "Prima linea nel colpo di calore.", risposta: "Raffreddamento fisico rapido (ghiaccio, coperte/immersione in acqua fredda) + reidratazione; NO antipiretici."},
  {id: 7, argomento: "Febbre e antipiretici", domanda: "Trattamento della sindrome neurolettica maligna.", risposta: "Sospendere il neurolettico, raffreddamento, idratazione, dantrolene (± bromocriptina) e benzodiazepine per l'agitazione."},
  {id: 8, argomento: "Febbre e antipiretici", domanda: "Paziente in terapia con amitriptilina con febbre >41,5°C: prima terapia?", risposta: "Sospendere il farmaco e raffreddare il paziente (sospetta sindrome ipertermica da serotoninergici/anticolinergici)."},
  {id: 9, argomento: "Febbre e antipiretici", domanda: "Paziente con tramadolo + antidepressivo (SSRI) sviluppa diarrea, confusione, crampi, ipotensione: cosa ha assunto?", risposta: "Un SSRI/serotoninergico → sindrome serotoninergica (sospendere e raffreddare)."},
  {id: 10, argomento: "Febbre e antipiretici", domanda: "Una donna in gravidanza ha febbre a 38,5°C mal tollerata: quale antipiretico preferisci e quale eviti?", risposta: "Preferire il paracetamolo (sicuro in gravidanza); evitare i FANS, soprattutto nel terzo trimestre (chiusura precoce del dotto di Botallo)."},
  {id: 11, argomento: "Febbre e antipiretici", domanda: "Qual è la dose massima giornaliera di paracetamolo nell'adulto e qual è l'organo bersaglio in caso di sovradosaggio?", risposta: "Max 3-4 g/die; in sovradosaggio è epatotossico (necrosi epatica), antidoto N-acetilcisteina."},
  {id: 12, argomento: "Febbre e antipiretici", domanda: "Che cosa distingue febbre e ipertermia?", risposta: "Febbre: innalzamento del set-point ipotalamico; ipertermia: aumento termico senza aumento del set-point, da mancata dispersione del calore."},
  {id: 13, argomento: "Febbre e antipiretici", domanda: "Quando si parla di iperpiressia?", risposta: "Temperatura ≥41,5°C, emergenza per rischio di MOF e danno neurologico."},
  {id: 14, argomento: "Febbre e antipiretici", domanda: "Quali pirogeni endogeni inducono febbre?", risposta: "IL-1α, IL-1β, IL-6, TNF e IFNα."},
  {id: 15, argomento: "Febbre e antipiretici", domanda: "Qual è il ruolo della PGE2 nella febbre?", risposta: "Aumenta il set-point ipotalamico dopo produzione tramite COX nelle cellule endoteliali cerebrali."},
  {id: 16, argomento: "Febbre e antipiretici", domanda: "Dose antipiretica dell'aspirina nell'adulto.", risposta: "350-500 mg per os ogni 4-6 ore."},
  {id: 17, argomento: "Febbre e antipiretici", domanda: "Dose pediatrica del paracetamolo nella febbre.", risposta: "10 mg/kg per os ogni 4-6 ore."},
  {id: 18, argomento: "Febbre e antipiretici", domanda: "Perché l'indometacina è usata nelle febbri ematologiche?", risposta: "Riduce prostaglandine e citochine; dose 25-50 mg per os ogni 6-8 ore, ma è molto gastro-lesiva."},
  {id: 19, argomento: "Febbre e antipiretici", domanda: "Come tratti l'ipertermia da colpo di calore?", risposta: "Raffreddamento fisico rapido con ghiaccio/mezzi fisici; gli antipiretici non sono il trattamento cardine."},

  // --- 2. TERAPIA DEL DOLORE ------------------------------------------
  {id: 20, argomento: "Terapia del dolore", domanda: "Nomina un FANS non selettivo, uno selettivo COX-2 e uno relativamente COX-1.", risposta: "Non selettivo: ibuprofene; COX-2 selettivo: etoricoxib (o celecoxib); più COX-1: ketorolac (o aspirina/indometacina)."},
  {id: 21, argomento: "Terapia del dolore", domanda: "Inibitori COX-2 con posologia.", risposta: "Etoricoxib 30-120 mg/die; celecoxib 200-400 mg/die."},
  {id: 22, argomento: "Terapia del dolore", domanda: "In quali condizioni i FANS accentuano la tossicità intestinale?", risposta: "Digiuno, uso prolungato/ad alte dosi, terapia multipla con FANS, associazione con steroidi, anticoagulanti o SSRI."},
  {id: 23, argomento: "Terapia del dolore", domanda: "Nomina 4 oppioidi forti e 2 deboli.", risposta: "Forti: morfina, ossicodone, fentanyl, buprenorfina. Deboli: codeina, tramadolo."},
  {id: 24, argomento: "Terapia del dolore", domanda: "In ordine decrescente di potenza: fentanyl, ossicodone, codeina.", risposta: "Fentanyl > ossicodone > codeina."},
  {id: 25, argomento: "Terapia del dolore", domanda: "Oppioide debole, agonista μ + inibizione reuptake serotonina/noradrenalina: quale farmaco?", risposta: "Tramadolo."},
  {id: 26, argomento: "Terapia del dolore", domanda: "Cosa associ all'ossicodone per ridurne la stipsi?", risposta: "Naloxone (associazione ossicodone+naloxone = Targin)."},
  {id: 27, argomento: "Terapia del dolore", domanda: "Paziente in morfina con controllo sub-ottimale aggiunge codeina: cosa ti aspetti?", risposta: "Nessun miglioramento: la codeina è un oppioide debole, non potenzia la morfina."},
  {id: 28, argomento: "Terapia del dolore", domanda: "Antidepressivo usato nel dolore neuropatico.", risposta: "Amitriptilina o duloxetina."},
  {id: 29, argomento: "Terapia del dolore", domanda: "Modalità di somministrazione preferibile del fentanyl nel dolore cronico.", risposta: "Transdermica (cerotto)."},
  {id: 30, argomento: "Terapia del dolore", domanda: "FANS al terzo trimestre di gravidanza: quale effetto sul feto?", risposta: "Chiusura precoce del dotto di Botallo (controindicati nel 3° trimestre)."},
  {id: 31, argomento: "Terapia del dolore", domanda: "Buprenorfina: cos'è?", risposta: "Oppioide forte agonista parziale del recettore μ (e antagonista κ); usata nel dolore cronico e nella dipendenza da oppioidi."},
  {id: 32, argomento: "Terapia del dolore", domanda: "Descrivi i tre gradini della scala OMS del dolore.", risposta: "1° FANS/paracetamolo; 2° oppioidi deboli (codeina, tramadolo) ± non-oppioidi; 3° oppioidi forti (morfina) ± non-oppioidi e adiuvanti."},
  {id: 33, argomento: "Terapia del dolore", domanda: "Quale effetto collaterale degli oppioidi NON va incontro a tolleranza e va sempre trattato in profilassi?", risposta: "La stipsi: va sempre prevenuta con lassativi, mentre nausea e sedazione tendono a ridursi nel tempo."},
  {id: 34, argomento: "Terapia del dolore", domanda: "Quali farmaci usi come adiuvanti nel dolore neuropatico?", risposta: "Antiepilettici (gabapentin, pregabalina) e antidepressivi (amitriptilina, duloxetina)."},
  {id: 35, argomento: "Terapia del dolore", domanda: "Perché il paracetamolo non è antinfiammatorio come i FANS?", risposta: "Agisce soprattutto centralmente su COX-3 e poco in periferia."},
  {id: 36, argomento: "Terapia del dolore", domanda: "Quale dose di paracetamolo è analgesica nell'adulto?", risposta: "Circa 1000 mg, superiore alla dose antipiretica di 500 mg."},
  {id: 37, argomento: "Terapia del dolore", domanda: "Perché associare PPI a FANS prolungati?", risposta: "Per ridurre gastrolesività da inibizione COX-1; esempi: pantoprazolo/esomeprazolo 40 mg, omeprazolo 20 mg."},
  {id: 38, argomento: "Terapia del dolore", domanda: "Quale oppioide debole inibisce anche reuptake di serotonina/noradrenalina?", risposta: "Tramadolo."},
  {id: 39, argomento: "Terapia del dolore", domanda: "Quale adiuvante antidepressivo usi nel dolore neuropatico?", risposta: "Amitriptilina o duloxetina."},
  {id: 40, argomento: "Terapia del dolore", domanda: "Perché prevenire sempre la stipsi da oppioidi?", risposta: "È un effetto collaterale che non sviluppa tolleranza e richiede profilassi con lassativi."},
  {id: 41, argomento: "Terapia del dolore", domanda: "Quali adiuvanti antiepilettici usi nel dolore neuropatico?", risposta: "Gabapentin o pregabalin."},
  {id: 42, argomento: "Terapia del dolore", domanda: "Quale rischio hanno FANS e gravidanza avanzata?", risposta: "Chiusura precoce del dotto di Botallo, soprattutto nel terzo trimestre."},

  // --- 3. INFEZIONI VIE AEREE SUPERIORI -------------------------------
  {id: 43, argomento: "Infezioni vie aeree superiori", domanda: "Bambino con mal di gola, essudato, febbre, NO tosse, linfonodi laterocervicali ingrossati: iter diagnostico-terapeutico.", risposta: "Sospetto SBEGA: applico il Centor score, eseguo tampone faringeo e tratto con amoxicillina (o penicillina G IM in dose unica)."},
  {id: 44, argomento: "Infezioni vie aeree superiori", domanda: "SBEGA: terapia di prima linea.", risposta: "Amoxicillina 50 mg/kg/die (max 1 g) x2 per 10 gg, oppure penicillina G benzatina IM monodose."},
  {id: 45, argomento: "Infezioni vie aeree superiori", domanda: "SBEGA con allergia a penicillina: seconda linea con dosaggi.", risposta: "Azitromicina 12 mg/kg/die (max 500 mg) x5 gg, oppure claritromicina, oppure clindamicina."},
  {id: 46, argomento: "Infezioni vie aeree superiori", domanda: "Dolore frontale alla digitopressione da 10 giorni: cosa dai?", risposta: "Sinusite batterica: amoxicillina-clavulanato 1 g ogni 8-12 h per 10 giorni."},
  {id: 47, argomento: "Infezioni vie aeree superiori", domanda: "Sinusite acuta senza beta-lattamici (allergia): cosa dai?", risposta: "Macrolide (claritromicina o azitromicina)."},
  {id: 48, argomento: "Infezioni vie aeree superiori", domanda: "Otite media acuta con versamento e bulging nel bambino: terapia.", risposta: "Amoxicillina 80-90 mg/kg/die per 7 gg (10 gg se <2 anni) + analgesia; se inefficace dopo 72 h → cefuroxime o ceftriaxone."},
  {id: 49, argomento: "Infezioni vie aeree superiori", domanda: "Otite media acuta senza bulging: cosa fare?", risposta: "Vigile attesa 48-72 h con analgesia; antibiotico solo se peggioramento o segni di bulging/otorrea."},
  {id: 50, argomento: "Infezioni vie aeree superiori", domanda: "Bambino con pertosse in fase catarrale: terapia.", risposta: "Azitromicina (10 mg/kg il 1° giorno poi 5 mg/kg per 4 gg) il prima possibile."},
  {id: 51, argomento: "Infezioni vie aeree superiori", domanda: "Nomina 3 farmaci per la tosse (classi diverse).", risposta: "Sedativi centrali (destrometorfano, codeina), mucolitici (acetilcisteina, bromexina), decongestionanti/antistaminici."},
  {id: 52, argomento: "Infezioni vie aeree superiori", domanda: "Faringotonsillite streptococcica: antibiotico di prima scelta e alternativa in allergia alle penicilline.", risposta: "Prima scelta amoxicillina (o penicillina); in allergia un macrolide come azitromicina."},
  {id: 53, argomento: "Infezioni vie aeree superiori", domanda: "Perché nella maggior parte delle faringiti acute NON è indicato l'antibiotico?", risposta: "Perché la maggior parte ha eziologia virale; l'antibiotico si riserva alle forme batteriche (streptococco) documentate o ad alta probabilità."},
  {id: 54, argomento: "Infezioni vie aeree superiori", domanda: "Le placche tonsillari distinguono faringite batterica e virale?", risposta: "No: l'essudato può comparire anche nelle forme virali."},
  {id: 55, argomento: "Infezioni vie aeree superiori", domanda: "Criteri clinici di Centor per SBEGA.", risposta: "Essudato, linfoadenopatia cervicale anteriore dolente, febbre >38°C, assenza di tosse, età 3-15 anni."},
  {id: 56, argomento: "Infezioni vie aeree superiori", domanda: "Dose di penicillina G benzatina nella faringite SBEGA.", risposta: "600.000 UI IM se <27 kg; 1.200.000 UI IM se >27 kg."},
  {id: 57, argomento: "Infezioni vie aeree superiori", domanda: "Dose di amoxicillina nella faringite da SBEGA secondo dispensa.", risposta: "20 mg/kg bid, massimo 500 mg x2, per 10 giorni."},
  {id: 58, argomento: "Infezioni vie aeree superiori", domanda: "Terapia dell'angina di Vincent/Ludwig/Lemierre.", risposta: "β-lattamico più metronidazolo o clindamicina."},
  {id: 59, argomento: "Infezioni vie aeree superiori", domanda: "Quando sospetti sovrainfezione batterica nel raffreddore?", risposta: "Mancata risoluzione dopo 10 giorni o peggioramento dopo 5-7 giorni."},
  {id: 60, argomento: "Infezioni vie aeree superiori", domanda: "Dose fenilefrina nasale nel raffreddore.", risposta: "1-2 puff/narice ogni 4-6 ore per massimo 2-3 giorni."},
  {id: 61, argomento: "Infezioni vie aeree superiori", domanda: "Perché limitare decongestionanti nasali a pochi giorni?", risposta: "Tachifilassi e aumento effetti sistemici con rischio ipertensione/infarto."},

  // --- 4. INFLUENZA ---------------------------------------------------
  {id: 62, argomento: "Influenza", domanda: "4 fattori di rischio per influenza complicata.", risposta: "Età <2 o >65 anni, gravidanza, immunodepressione, obesità, malattie croniche (cardiopolmonari, diabete), residenza in RSA."},
  {id: 63, argomento: "Influenza", domanda: "Effetti collaterali dello zanamivir.", risposta: "Broncospasmo e tosse (controindicato in asmatici/BPCO), cefalea, nausea."},
  {id: 64, argomento: "Influenza", domanda: "Effetti collaterali dell'oseltamivir.", risposta: "Nausea, vomito, dolore addominale, cefalea; raramente disturbi neuropsichiatrici (delirio nel bambino)."},
  {id: 65, argomento: "Influenza", domanda: "Effetti collaterali degli adamantani.", risposta: "Ansia, insonnia, allucinazioni, delirio."},
  {id: 66, argomento: "Influenza", domanda: "Classe di antivirali che dà alte resistenze dopo pochi giorni d'uso.", risposta: "Adamantani (amantadina/rimantadina)."},
  {id: 67, argomento: "Influenza", domanda: "Qual è il principale farmaco antivirale per l'influenza e quando è più efficace?", risposta: "Oseltamivir (inibitore della neuraminidasi); massima efficacia se iniziato entro 48 h dall'esordio dei sintomi."},
  {id: 68, argomento: "Influenza", domanda: "Quali proteine virali sono bersaglio anticorpale nell'influenza?", risposta: "Emoagglutinina e neuraminidasi."},
  {id: 69, argomento: "Influenza", domanda: "Differenza tra drift e shift antigenico.", risposta: "Drift: mutazioni minori ed epidemie; shift: riassortimento maggiore, pandemie, solo influenza A."},
  {id: 70, argomento: "Influenza", domanda: "Quando inizia lo shedding virale nell'influenza?", risposta: "24-48 ore prima dei sintomi, con picco nei primi 5 giorni."},
  {id: 71, argomento: "Influenza", domanda: "Chi va trattato con antivirali per influenza?", risposta: "Ospedalizzati e soggetti ad alto rischio di complicanze."},
  {id: 72, argomento: "Influenza", domanda: "Dose oseltamivir per influenza.", risposta: "75 mg per os bid per 5 giorni."},
  {id: 73, argomento: "Influenza", domanda: "Dose zanamivir secondo dispensa.", risposta: "2 puff/die, pari a 10 mg, per 5 giorni."},
  {id: 74, argomento: "Influenza", domanda: "Perché amantadina si usa poco?", risposta: "Solo influenza A, alte resistenze e ADR neuropsichiatrici."},
  {id: 75, argomento: "Influenza", domanda: "Controindicazione vera al vaccino antinfluenzale riportata.", risposta: "Allergia all'uovo."},

  // --- 5. COVID-19 ----------------------------------------------------
  {id: 76, argomento: "COVID-19", domanda: "Antivirale orale per il COVID.", risposta: "Nirmatrelvir/ritonavir (Paxlovid)."},
  {id: 77, argomento: "COVID-19", domanda: "Quando dare il desametasone nel COVID?", risposta: "Solo nel paziente ospedalizzato che necessita di ossigeno: desametasone 6 mg/die per 10 gg."},
  {id: 78, argomento: "COVID-19", domanda: "Un anticitochinico approvato per il COVID e il suo target.", risposta: "Tocilizumab (anti-IL-6) o anakinra (antagonista del recettore IL-1)."},
  {id: 79, argomento: "COVID-19", domanda: "Quale biologico inficia la produzione di anticorpi anti-COVID (e risposta vaccinale)?", risposta: "Rituximab (anti-CD20)."},
  {id: 80, argomento: "COVID-19", domanda: "Effetto collaterale raro del vaccino a vettore virale per COVID.", risposta: "Trombosi con trombocitopenia (VITT), mediata da anticorpi anti-PF4."},
  {id: 81, argomento: "COVID-19", domanda: "Paziente COVID ipossiemico in ossigenoterapia a basso flusso: quale schema terapeutico?", risposta: "Remdesivir + desametasone 6 mg/die per circa 10 giorni."},
  {id: 82, argomento: "COVID-19", domanda: "Qual è l'antivirale orale precoce per COVID a rischio di progressione e una sua importante criticità?", risposta: "Nirmatrelvir/ritonavir (Paxlovid); attenzione alle numerose interazioni farmacologiche legate al ritonavir."},
  {id: 83, argomento: "COVID-19", domanda: "Quale recettore usa SARS-CoV-2?", risposta: "ACE2, tramite proteina Spike."},
  {id: 84, argomento: "COVID-19", domanda: "Quattro meccanismi di danno del COVID.", risposta: "Danno epiteliale respiratorio, disregolazione Ang II, danno endoteliale, tempesta citochinica."},
  {id: 85, argomento: "COVID-19", domanda: "Criteri di COVID severo.", risposta: "SpO2 <94%, PaO2/FiO2 <300, RR >30 o infiltrati >50%, con necessità di ossigeno."},
  {id: 86, argomento: "COVID-19", domanda: "Quando usare antivirali nel COVID?", risposta: "Nelle fasi iniziali, idealmente entro 5-6 giorni, quando prevale la replicazione virale."},
  {id: 87, argomento: "COVID-19", domanda: "Schema remdesivir in COVID con O2 a basso flusso.", risposta: "200 mg EV giorno 1, poi 100 mg/die per 5-10 giorni, con desametasone."},
  {id: 88, argomento: "COVID-19", domanda: "Dose desametasone nel COVID severo.", risposta: "6 mg/die per os o EV per 10 giorni."},
  {id: 89, argomento: "COVID-19", domanda: "Dose LMWH profilattica nel COVID secondo dispensa.", risposta: "4000 U sottocute in bolo."},
  {id: 90, argomento: "COVID-19", domanda: "Controindicazione vera al vaccino COVID nella dispensa.", risposta: "Allergia al PEG, polietilene glicole."},

  // --- 6. POLMONITI ---------------------------------------------------
  {id: 91, argomento: "Polmoniti", domanda: "CAP senza allergie e senza fattori di rischio per MDR: terapia.", risposta: "Amoxicillina-clavulanato (o cefalosporina di 2ª/3ª gen.) + macrolide (azitromicina o claritromicina)."},
  {id: 92, argomento: "Polmoniti", domanda: "CAP in paziente allergico ai β-lattamici.", risposta: "Fluorochinolone respiratorio: levofloxacina 750 mg o moxifloxacina 400 mg."},
  {id: 93, argomento: "Polmoniti", domanda: "2 farmaci per CAP da MRSA.", risposta: "Vancomicina o linezolid (associati alla terapia per CAP standard)."},
  {id: 94, argomento: "Polmoniti", domanda: "Polmonite ab ingestis con ascesso: terapia.", risposta: "Piperacillina-tazobactam o carbapenemico + metronidazolo o clindamicina."},
  {id: 95, argomento: "Polmoniti", domanda: "HAP senza fattori di rischio MDR.", risposta: "Piperacillina-tazobactam (oppure cefepime/levofloxacina) a copertura di Pseudomonas."},
  {id: 96, argomento: "Polmoniti", domanda: "HAP >7 giorni (tardiva): terapia.", risposta: "Antipseudomonas: ceftazidime o piperacillina-tazobactam o meropenem + (levofloxacina/ciprofloxacina o amikacina)."},
  {id: 97, argomento: "Polmoniti", domanda: "HAP con MDR e sospetto MRSA.", risposta: "Carbapenemico (o pip-tazo) + (levofloxacina o amikacina) + (vancomicina/linezolid/teicoplanina)."},
  {id: 98, argomento: "Polmoniti", domanda: "Polmonite acuta in paziente epilettico in fenobarbital.", risposta: "Amoxicillina-clavulanato + azitromicina; evitare chinoloni e carbapenemici (abbassano la soglia convulsiva)."},
  {id: 99, argomento: "Polmoniti", domanda: "A cosa serve il CURB-65 e quali parametri valuta?", risposta: "Stratifica la gravità della CAP e la sede di cura: Confusione, Urea, Frequenza Respiratoria, Blood pressure, età ≥65 anni."},
  {id: 100, argomento: "Polmoniti", domanda: "Quali categorie di polmonite sono citate?", risposta: "CAP, HAP, HCAP e VAP."},
  {id: 101, argomento: "Polmoniti", domanda: "Quale score orienta gravità e sede di cura nella CAP?", risposta: "CURB-65."},
  {id: 102, argomento: "Polmoniti", domanda: "Patogeni tipici della CAP.", risposta: "S. pneumoniae, H. influenzae, Mycoplasma, Chlamydia, Legionella e virus respiratori."},
  {id: 103, argomento: "Polmoniti", domanda: "Perché associare β-lattamico e macrolide nella CAP severa?", risposta: "Per coprire pneumococco e atipici, con possibile effetto immunomodulante del macrolide."},
  {id: 104, argomento: "Polmoniti", domanda: "Terapia CAP in allergia ai β-lattamici.", risposta: "Fluorochinolone respiratorio, ad es. levofloxacina 750 mg o moxifloxacina 400 mg."},
  {id: 105, argomento: "Polmoniti", domanda: "Terapia se sospetto MRSA in CAP.", risposta: "Aggiungere vancomicina o linezolid."},
  {id: 106, argomento: "Polmoniti", domanda: "Perché HAP/VAP richiedono copertura MDR?", risposta: "Per rischio di flora ospedaliera, Gram-negativi, Pseudomonas e MRSA."},
  {id: 107, argomento: "Polmoniti", domanda: "Cosa fare se CAP non migliora?", risposta: "Rivalutare diagnosi, imaging, colture, complicanze, atipici/resistenze e adeguatezza antibiotica."},

  // --- 7. TUBERCOLOSI -------------------------------------------------
  {id: 108, argomento: "Tubercolosi", domanda: "Terapia della TBC latente: farmaco, dose e durata.", risposta: "Isoniazide 5 mg/kg/die per 6-9 mesi, oppure rifampicina 10 mg/kg per 4 mesi, oppure entrambe per 3 mesi."},
  {id: 109, argomento: "Tubercolosi", domanda: "Farmaci della terapia iniziale della TBC attiva.", risposta: "Isoniazide + rifampicina + etambutolo + pirazinamide (fase intensiva 2 mesi)."},
  {id: 110, argomento: "Tubercolosi", domanda: "Isoniazide: quale effetto collaterale dà e come lo previeni?", risposta: "Neuropatia periferica; si previene con vitamina B6 (piridossina)."},
  {id: 111, argomento: "Tubercolosi", domanda: "Quale anti-TBC ha più interazioni farmacologiche?", risposta: "Rifampicina (potente induttore enzimatico del CYP450)."},
  {id: 112, argomento: "Tubercolosi", domanda: "Qual è lo schema standard della TBC polmonare e la sua durata?", risposta: "2 mesi di fase intensiva con H+R+Z+E, seguiti da 4 mesi di continuazione con H+R (6 mesi totali)."},
  {id: 113, argomento: "Tubercolosi", domanda: "Quale tossicità specifica va monitorata con l'etambutolo?", risposta: "La neurite ottica (alterazioni del visus e della discriminazione dei colori)."},
  {id: 114, argomento: "Tubercolosi", domanda: "Quali campioni per TBC polmonare?", risposta: "Due espettorati ≥5 mL a distanza di almeno 8 ore, uno mattutino; se non possibile BAL."},
  {id: 115, argomento: "Tubercolosi", domanda: "Quali test sull'espettorato per TBC?", risposta: "Ziehl-Neelsen, coltura e PCR."},
  {id: 116, argomento: "Tubercolosi", domanda: "Schema standard TBC attiva.", risposta: "2 mesi isoniazide+rifampicina+pirazinamide+etambutolo, poi 4 mesi isoniazide+rifampicina."},
  {id: 117, argomento: "Tubercolosi", domanda: "Effetto collaterale isoniazide e prevenzione.", risposta: "Neuropatia periferica; prevenzione con vitamina B6/piridossina."},
  {id: 118, argomento: "Tubercolosi", domanda: "Effetto tipico della rifampicina.", risposta: "Colorazione arancione delle secrezioni e molte interazioni per induzione enzimatica."},
  {id: 119, argomento: "Tubercolosi", domanda: "Tossicità etambutolo.", risposta: "Neurite ottica con alterazioni del visus/colori."},
  {id: 120, argomento: "Tubercolosi", domanda: "Tossicità pirazinamide.", risposta: "Epatotossicità e iperuricemia."},
  {id: 121, argomento: "Tubercolosi", domanda: "Perché terapia TBC usa più farmaci?", risposta: "Per aumentare efficacia e prevenire selezione di resistenze."},

  // --- 8. ENDOCARDITI INFETTIVE ---------------------------------------
  {id: 122, argomento: "Endocarditi infettive", domanda: "Endocardite da streptococco penicillino-sensibile su valvola nativa.", risposta: "Ceftriaxone 2 g IV/die per 4 settimane (± gentamicina per 2 settimane); vancomicina se allergico."},
  {id: 123, argomento: "Endocarditi infettive", domanda: "Endocardite da S. aureus meticillino-sensibile (MSSA) su valvola nativa.", risposta: "Oxacillina/nafcillina (± gentamicina opzionale)."},
  {id: 124, argomento: "Endocarditi infettive", domanda: "Endocardite da MSSA su valvola protesica.", risposta: "Oxacillina/nafcillina + rifampicina + gentamicina."},
  {id: 125, argomento: "Endocarditi infettive", domanda: "In quale endocardite si aggiunge rifampicina?", risposta: "Endocardite su valvola protesica da stafilococchi."},
  {id: 126, argomento: "Endocarditi infettive", domanda: "Endocardite da MRSA su valvola nativa.", risposta: "Vancomicina 30 mg/kg/die per 6 settimane (± gentamicina)."},
  {id: 127, argomento: "Endocarditi infettive", domanda: "Profilassi dell'endocardite prima di procedura odontoiatrica in paziente a rischio.", risposta: "Amoxicillina (o ampicillina) 2 g per os 30-60 min prima; se allergico azitromicina/claritromicina 500 mg o clindamicina 600 mg."},
  {id: 128, argomento: "Endocarditi infettive", domanda: "Perché nell'endocardite su protesi si aggiunge la rifampicina?", risposta: "Perché penetra bene nel biofilm e nei tessuti, utile contro i germi adesi al materiale protesico."},
  {id: 129, argomento: "Endocarditi infettive", domanda: "Perché fare emocolture prima degli antibiotici?", risposta: "Per identificare il patogeno; antibiotici prima del prelievo possono negativizzare le colture."},
  {id: 130, argomento: "Endocarditi infettive", domanda: "Principio della terapia dell'endocardite.", risposta: "Antibioticoterapia EV, mirata, prolungata e battericida."},
  {id: 131, argomento: "Endocarditi infettive", domanda: "Patogeno tipico di endocardite acuta aggressiva.", risposta: "Staphylococcus aureus."},
  {id: 132, argomento: "Endocarditi infettive", domanda: "Valvola tipica nel tossicodipendente EV.", risposta: "Tricuspide, con embolie settiche polmonari."},
  {id: 133, argomento: "Endocarditi infettive", domanda: "Complicanza embolica dell'endocardite sinistra.", risposta: "Ictus o embolie sistemiche a milza, rene o arti."},
  {id: 134, argomento: "Endocarditi infettive", domanda: "Quando pensi alla chirurgia nell'endocardite?", risposta: "Scompenso da danno valvolare, infezione non controllata, ascessi, protesi complicata o embolie ricorrenti."},
  {id: 135, argomento: "Endocarditi infettive", domanda: "Perché rifampicina nelle protesi stafilococciche?", risposta: "Penetra nel biofilm su materiale protesico."},
  {id: 136, argomento: "Endocarditi infettive", domanda: "Profilassi odontoiatrica nel paziente ad alto rischio.", risposta: "Amoxicillina 2 g per os 30-60 minuti prima; alternative macrolide/clindamicina se allergia."},

  // --- 9. INFEZIONI VIE URINARIE --------------------------------------
  {id: 137, argomento: "Infezioni vie urinarie", domanda: "Cistite non complicata: terapia con nome, dosaggio e durata.", risposta: "Prima linea: fosfomicina 3 g monodose, oppure nitrofurantoina 100 mg x2 per 5 gg."},
  {id: 138, argomento: "Infezioni vie urinarie", domanda: "Pielonefrite non complicata: farmaco di prima linea.", risposta: "Fluorochinolone: ciprofloxacina 500 mg x2 per 7 gg o levofloxacina 750 mg per 5 gg."},
  {id: 139, argomento: "Infezioni vie urinarie", domanda: "Pielonefrite in paziente gravida.", risposta: "Urinocoltura + test di gravidanza; ricovero ed empirica con β-lattamico (ceftriaxone); evitare fluorochinoloni e TMP-SMX."},
  {id: 140, argomento: "Infezioni vie urinarie", domanda: "Donna con 10 episodi di cistite/anno correlati al coito: profilassi.", risposta: "Profilassi post-coitale con nitrofurantoina 50-100 mg in dose singola."},
  {id: 141, argomento: "Infezioni vie urinarie", domanda: "Perché la nitrofurantoina non è indicata nella pielonefrite?", risposta: "Perché non raggiunge concentrazioni tissutali/parenchimali adeguate: agisce solo a livello urinario (cistite)."},
  {id: 142, argomento: "Infezioni vie urinarie", domanda: "Patogeno più frequente nelle IVU non complicate.", risposta: "Escherichia coli."},
  {id: 143, argomento: "Infezioni vie urinarie", domanda: "Sintomi tipici di cistite.", risposta: "Disuria, pollachiuria, urgenza, dolore sovrapubico senza febbre alta o dolore lombare."},
  {id: 144, argomento: "Infezioni vie urinarie", domanda: "Segni di pielonefrite.", risposta: "Febbre, brividi, dolore lombare/Giordano positivo, nausea-vomito e compromissione generale."},
  {id: 145, argomento: "Infezioni vie urinarie", domanda: "Terapia cistite non complicata.", risposta: "Fosfomicina 3 g monodose oppure nitrofurantoina 100 mg x2 per 5 giorni."},
  {id: 146, argomento: "Infezioni vie urinarie", domanda: "Perché nitrofurantoina non nella pielonefrite?", risposta: "Non raggiunge concentrazioni parenchimali adeguate."},
  {id: 147, argomento: "Infezioni vie urinarie", domanda: "Quando fare urinocoltura?", risposta: "Pielonefrite, gravidanza, maschio, IVU complicata, recidive o fallimento terapeutico."},
  {id: 148, argomento: "Infezioni vie urinarie", domanda: "Quando trattare batteriuria asintomatica?", risposta: "Soprattutto gravidanza o procedure urologiche selezionate; non di routine."},
  {id: 149, argomento: "Infezioni vie urinarie", domanda: "Profilassi post-coitale nella cistite recidivante.", risposta: "Nitrofurantoina 50-100 mg in dose singola post-coitale."},

  // --- 10. PRINCIPI DI TERAPIA ANTIBIOTICA -----------------------------
  {id: 150, argomento: "Principi di terapia antibiotica", domanda: "Farmaco attivo solo su Gram+, buon assorbimento orale e buona distribuzione tissutale.", risposta: "Linezolid."},
  {id: 151, argomento: "Principi di terapia antibiotica", domanda: "Un'indicazione per la vancomicina per os.", risposta: "Infezione da Clostridioides difficile (colite pseudomembranosa)."},
  {id: 152, argomento: "Principi di terapia antibiotica", domanda: "In quale sede NON si usa la daptomicina?", risposta: "Nel polmone (è inattivata dal surfattante)."},
  {id: 153, argomento: "Principi di terapia antibiotica", domanda: "3 effetti avversi dei fluorochinoloni.", risposta: "Tendinopatia/rottura tendinea, allungamento del QT, abbassamento della soglia convulsiva (+ disglicemie, fototossicità)."},
  {id: 154, argomento: "Principi di terapia antibiotica", domanda: "Effetti collaterali della gentamicina.", risposta: "Nefrotossicità, ototossicità, tossicità GI, blocco neuromuscolare."},
  {id: 155, argomento: "Principi di terapia antibiotica", domanda: "Antibiotico da non associare al metotrexato.", risposta: "Trimetoprim-sulfametossazolo (TMP-SMX), per antagonismo sui folati e tossicità midollare additiva."},
  {id: 156, argomento: "Principi di terapia antibiotica", domanda: "Quale cefalosporina di 3ª ha azione su Pseudomonas?", risposta: "Ceftazidime."},
  {id: 157, argomento: "Principi di terapia antibiotica", domanda: "Che differenza c'è tra terapia antibiotica empirica e mirata?", risposta: "L'empirica si basa sul sospetto clinico/epidemiologico prima dell'antibiogramma; la mirata segue l'isolamento del germe e la sua sensibilità."},
  {id: 158, argomento: "Principi di terapia antibiotica", domanda: "Differenza tra terapia empirica e mirata.", risposta: "Empirica su sospetto clinico; mirata su isolamento microbiologico e antibiogramma."},
  {id: 159, argomento: "Principi di terapia antibiotica", domanda: "Che cos'è de-escalation antibiotica?", risposta: "Restringere spettro/semplificare terapia quando arrivano microbiologia e risposta clinica."},
  {id: 160, argomento: "Principi di terapia antibiotica", domanda: "Perché rivalutare antibiotico a 48-72 ore?", risposta: "Per risposta clinica, colture, tossicità e possibilità di de-escalation."},
  {id: 161, argomento: "Principi di terapia antibiotica", domanda: "Perché conoscere il sito d'infezione?", risposta: "Il farmaco deve raggiungere concentrazioni efficaci nel tessuto infetto."},
  {id: 162, argomento: "Principi di terapia antibiotica", domanda: "Perché daptomicina non si usa nel polmone?", risposta: "È inattivata dal surfattante."},
  {id: 163, argomento: "Principi di terapia antibiotica", domanda: "Un'indicazione di vancomicina per os.", risposta: "Colite da Clostridioides difficile."},
  {id: 164, argomento: "Principi di terapia antibiotica", domanda: "Tre ADR dei fluorochinoloni.", risposta: "Tendinopatia/rottura, QT lungo, abbassamento soglia convulsiva; anche disglicemie/fototossicità."},
  {id: 165, argomento: "Principi di terapia antibiotica", domanda: "Antibiotico da evitare con metotrexato.", risposta: "TMP-SMX per tossicità midollare additiva e antagonismo dei folati."},

  // --- 11. SEPSI E SHOCK SETTICO ---------------------------------------
  {id: 166, argomento: "Sepsi e shock settico", domanda: "Tre azioni iniziali nella sepsi (sepsis six).", risposta: "Ossigenoterapia, emocolture (prima degli antibiotici) e antibioticoterapia empirica precoce; + fluidi, lattati, diuresi."},
  {id: 167, argomento: "Sepsi e shock settico", domanda: "Entro quanto tempo va iniziata la terapia antibiotica nella sepsi?", risposta: "Entro 1 ora dal riconoscimento (≤60 minuti)."},
  {id: 168, argomento: "Sepsi e shock settico", domanda: "Tre vasopressori nello shock settico.", risposta: "Noradrenalina (1ª scelta), vasopressina (ADH), adrenalina/dopamina come aggiunta."},
  {id: 169, argomento: "Sepsi e shock settico", domanda: "Cosa misuro nel sangue per stabilire la gravità della sepsi?", risposta: "Il lattato (la clearance dei lattati indica la risposta)."},
  {id: 170, argomento: "Sepsi e shock settico", domanda: "Definizione di shock settico.", risposta: "Sepsi con ipotensione persistente che richiede vasopressori per mantenere PAM ≥65 mmHg e lattati >2 mmol/L nonostante adeguata rianimazione volemica."},
  {id: 171, argomento: "Sepsi e shock settico", domanda: "Definizione pratica di SIRS.", risposta: "Almeno due tra T >38/<36, FC >90, FR >20 o PaCO2 <32, WBC >12.000/<4.000 o immature >10%."},
  {id: 172, argomento: "Sepsi e shock settico", domanda: "Cosa distingue sepsi e shock settico?", risposta: "Shock: sepsi con ipotensione persistente/necessità vasopressori e ipoperfusione nonostante fluidi."},
  {id: 173, argomento: "Sepsi e shock settico", domanda: "Entro quanto iniziare antibiotico nello shock settico?", risposta: "Entro 1 ora dal riconoscimento."},
  {id: 174, argomento: "Sepsi e shock settico", domanda: "Vasopressore di prima scelta nello shock settico.", risposta: "Noradrenalina."},
  {id: 175, argomento: "Sepsi e shock settico", domanda: "Target PAM nello shock settico.", risposta: "PAM ≥65 mmHg."},
  {id: 176, argomento: "Sepsi e shock settico", domanda: "Perché misurare lattato?", risposta: "Marker di ipoperfusione e gravità; la clearance orienta risposta."},
  {id: 177, argomento: "Sepsi e shock settico", domanda: "Che cos'è source control?", risposta: "Drenare/rimuovere il focolaio infettivo: ascesso, catetere, ostruzione, perforazione, necrosi."},
  {id: 178, argomento: "Sepsi e shock settico", domanda: "Cita tre azioni del sepsis six.", risposta: "Ossigeno, emocolture, antibiotico precoce, fluidi, lattato, monitoraggio diuresi."},

  // --- 12. SINDROMI CORONARICHE ACUTE ----------------------------------
  {id: 179, argomento: "Sindromi coronariche acute", domanda: "Tre farmaci da usare come DAPT (oltre all'aspirina) pre-PCI.", risposta: "Aspirina + uno tra ticagrelor 180 mg, prasugrel 60 mg (se diabetico) o clopidogrel 300-600 mg (se alto rischio emorragico)."},
  {id: 180, argomento: "Sindromi coronariche acute", domanda: "Tre farmaci che non possono mancare dopo uno STEMI.", risposta: "DAPT (aspirina + ticagrelor/prasugrel) per 12 mesi, statina ad alta intensità e ACE-inibitore (± β-bloccante)."},
  {id: 181, argomento: "Sindromi coronariche acute", domanda: "Almeno 3 controindicazioni alla trombolisi sistemica nell'infarto.", risposta: "Emorragia intracranica pregressa, ictus ischemico <3 mesi, dissezione aortica, trauma cranico recente, sanguinamento attivo."},
  {id: 182, argomento: "Sindromi coronariche acute", domanda: "Perché la morfina è rischiosa nell'infarto acuto?", risposta: "Rallenta lo svuotamento gastrico e l'assorbimento degli antiaggreganti orali (DAPT), riducendone l'efficacia."},
  {id: 183, argomento: "Sindromi coronariche acute", domanda: "STEMI a 3 ore da un centro hub: cosa fai sul territorio?", risposta: "Trombolisi farmacologica (se non controindicata) + DAPT, statina, controllo del dolore e ossigeno se necessario."},
  {id: 184, argomento: "Sindromi coronariche acute", domanda: "Dose di carico di ticagrelor e di clopidogrel nella SCA.", risposta: "Ticagrelor 180 mg (2 cp da 90 mg); clopidogrel 600 mg (2 cp da 300 mg)."},
  {id: 185, argomento: "Sindromi coronariche acute", domanda: "Per quanto tempo si prosegue di norma la DAPT dopo una SCA?", risposta: "Di solito 12 mesi, poi si prosegue con un singolo antiaggregante; la durata si modula sul rischio ischemico/emorragico."},
  {id: 186, argomento: "Sindromi coronariche acute", domanda: "Causa più frequente di SCA.", risposta: "Trombo su placca vulnerabile da rottura o erosione."},
  {id: 187, argomento: "Sindromi coronariche acute", domanda: "Trombo occlusivo vs non occlusivo nella SCA.", risposta: "Occlusivo: STEMI; non occlusivo: angina instabile o NSTEMI se necrosi."},
  {id: 188, argomento: "Sindromi coronariche acute", domanda: "Biomarcatore di necrosi miocardica.", risposta: "Troponina."},
  {id: 189, argomento: "Sindromi coronariche acute", domanda: "Obiettivo nello STEMI.", risposta: "Riperfusione urgente, preferibilmente PCI primaria se disponibile."},
  {id: 190, argomento: "Sindromi coronariche acute", domanda: "Dose carico ticagrelor nella SCA.", risposta: "180 mg."},
  {id: 191, argomento: "Sindromi coronariche acute", domanda: "Dose carico clopidogrel nella SCA.", risposta: "300-600 mg, spesso 600 mg pre-PCI."},
  {id: 192, argomento: "Sindromi coronariche acute", domanda: "Durata usuale DAPT dopo SCA.", risposta: "Circa 12 mesi, modulando su rischio ischemico/emorragico."},
  {id: 193, argomento: "Sindromi coronariche acute", domanda: "Perché morfina può essere problematica nell'infarto?", risposta: "Rallenta svuotamento gastrico e assorbimento degli antiaggreganti orali."},

  // --- 13. CARDIOPATIA ISCHEMICA CRONICA -------------------------------
  {id: 194, argomento: "Cardiopatia ischemica cronica", domanda: "Prima linea nell'angina variante (di Prinzmetal).", risposta: "Calcio-antagonista ad alto dosaggio (es. diltiazem 360 mg); se insufficiente aggiungere nitrato a lunga durata."},
  {id: 195, argomento: "Cardiopatia ischemica cronica", domanda: "Vasodilatatori sublinguali che il paziente può assumere prima di arrivare in ospedale.", risposta: "Nitroglicerina (trinitrina) sublinguale, ripetibile fino a 3 volte."},
  {id: 196, argomento: "Cardiopatia ischemica cronica", domanda: "Condizioni in cui si preferisce il bypass (CABG).", risposta: "Malattia multivasale estesa, diabete, alto rischio emorragico (per evitare DAPT prolungata)."},
  {id: 197, argomento: "Cardiopatia ischemica cronica", domanda: "Qual è la terapia antianginosa di prima linea per il controllo dei sintomi?", risposta: "I beta-bloccanti (e/o calcio-antagonisti); nitrati a breve durata per le crisi."},
  {id: 198, argomento: "Cardiopatia ischemica cronica", domanda: "Obiettivi della terapia antianginosa cronica.", risposta: "Ridurre sintomi, ischemia e consumo miocardico di O2."},
  {id: 199, argomento: "Cardiopatia ischemica cronica", domanda: "Prima linea sintomatica nell'angina cronica.", risposta: "Beta-bloccanti e/o calcio-antagonisti; nitrati a breve durata per crisi."},
  {id: 200, argomento: "Cardiopatia ischemica cronica", domanda: "Terapia dell'angina variante.", risposta: "Calcio-antagonisti ad alte dosi, eventualmente nitrati a lunga durata."},
  {id: 201, argomento: "Cardiopatia ischemica cronica", domanda: "Perché nitrati e PDE5-inibitori sono controindicati insieme?", risposta: "Rischio di ipotensione severa da eccesso NO-cGMP."},
  {id: 202, argomento: "Cardiopatia ischemica cronica", domanda: "Quando preferire CABG.", risposta: "Malattia multivasale estesa, diabete, anatomia complessa o alto rischio emorragico per DAPT."},
  {id: 203, argomento: "Cardiopatia ischemica cronica", domanda: "Ruolo dell'aspirina nella coronaropatia cronica.", risposta: "Prevenzione secondaria antiaggregante."},
  {id: 204, argomento: "Cardiopatia ischemica cronica", domanda: "Ruolo della statina nella coronaropatia cronica.", risposta: "Stabilizza/riduce placca e riduce eventi cardiovascolari."},
  {id: 205, argomento: "Cardiopatia ischemica cronica", domanda: "Che cosa indica calcium score 0 alla TC coronarica?", risposta: "Assenza di calcificazioni coronariche e gestione prevalentemente dei fattori di rischio."},

  // --- 14. DISLIPIDEMIE ------------------------------------------------
  {id: 206, argomento: "Dislipidemie", domanda: "Paziente con statine al massimo dosaggio: cosa aggiungi per ridurre ulteriormente le LDL?", risposta: "Ezetimibe; poi acido bempedoico; poi inibitore PCSK9 (evolocumab/alirocumab); infine inclisiran."},
  {id: 207, argomento: "Dislipidemie", domanda: "Meccanismo d'azione dell'ezetimibe.", risposta: "Riduce l'assorbimento intestinale del colesterolo bloccando il trasportatore NPC1L1."},
  {id: 208, argomento: "Dislipidemie", domanda: "Come agiscono gli inibitori di PCSK9?", risposta: "Bloccano PCSK9 impedendo la degradazione del recettore LDL epatico → più recettori → maggiore captazione di LDL."},
  {id: 209, argomento: "Dislipidemie", domanda: "Cos'è inclisiran?", risposta: "Piccolo RNA interferente (siRNA) che silenzia PCSK9; riduce le LDL con somministrazione semestrale."},
  {id: 210, argomento: "Dislipidemie", domanda: "Statina da NON usare nell'insufficienza renale grave.", risposta: "Rosuvastatina (escrezione renale)."},
  {id: 211, argomento: "Dislipidemie", domanda: "Effetti collaterali delle statine.", risposta: "Mialgie/miopatia (rara rabdomiolisi e miopatia autoimmune), aumento transaminasi, peggioramento del controllo glicemico."},
  {id: 212, argomento: "Dislipidemie", domanda: "Target LDL in uomo 60 anni diabetico non coronaropatico.", risposta: "<70 mg/dL (rischio alto); <55 mg/dL se rischio molto alto o danno d'organo."},
  {id: 213, argomento: "Dislipidemie", domanda: "Quando si sospende una statina per tossicità epatica?", risposta: "Quando le transaminasi superano 3 volte il limite superiore di norma."},
  {id: 214, argomento: "Dislipidemie", domanda: "Classi di farmaci per abbassare i trigliceridi in ordine di potenza.", risposta: "Fibrati > omega-3 > acido nicotinico > statine > ezetimibe."},
  {id: 215, argomento: "Dislipidemie", domanda: "Apo dei chilomicroni.", risposta: "ApoB48."},
  {id: 216, argomento: "Dislipidemie", domanda: "Apo di VLDL/IDL/LDL.", risposta: "ApoB100."},
  {id: 217, argomento: "Dislipidemie", domanda: "Meccanismo delle statine.", risposta: "Inibizione HMG-CoA reduttasi con aumento recettori LDL epatici."},
  {id: 218, argomento: "Dislipidemie", domanda: "Meccanismo ezetimibe.", risposta: "Blocco NPC1L1 e riduzione assorbimento intestinale del colesterolo."},
  {id: 219, argomento: "Dislipidemie", domanda: "Meccanismo PCSK9-inibitori.", risposta: "Evitano degradazione recettore LDL, aumentando clearance LDL."},
  {id: 220, argomento: "Dislipidemie", domanda: "Che cos'è inclisiran?", risposta: "siRNA che silenzia PCSK9 con somministrazione semestrale."},
  {id: 221, argomento: "Dislipidemie", domanda: "Quando sospendere statina per transaminasi?", risposta: "Se >3 volte il limite superiore di norma."},
  {id: 222, argomento: "Dislipidemie", domanda: "Rischio dei trigliceridi molto elevati.", risposta: "Pancreatite acuta."},

  // --- 15. ARITMIE E FIBRILLAZIONE ATRIALE -----------------------------
  {id: 223, argomento: "Aritmie e fibrillazione atriale", domanda: "Farmaco per la cardioversione farmacologica nel paziente cardiopatico.", risposta: "Amiodarone (sicuro in cardiopatia strutturale e scompenso)."},
  {id: 224, argomento: "Aritmie e fibrillazione atriale", domanda: "Farmaci per il 'pill in the pocket'.", risposta: "Flecainide o propafenone per os, in pazienti senza cardiopatia strutturale."},
  {id: 225, argomento: "Aritmie e fibrillazione atriale", domanda: "Prima linea nella tachicardia parossistica sopraventricolare (TPSV).", risposta: "Manovre vagali, poi adenosina ev in bolo rapido."},
  {id: 226, argomento: "Aritmie e fibrillazione atriale", domanda: "Cos'è il CHA2DS2-VASc?", risposta: "Score del rischio tromboembolico nella FA, usato per decidere l'anticoagulazione."},
  {id: 227, argomento: "Aritmie e fibrillazione atriale", domanda: "Amiodarone: effetti collaterali a lungo termine.", risposta: "Disfunzione tiroidea (ipo/ipertiroidismo), fibrosi polmonare, microdepositi corneali, epatotossicità, proaritmia."},
  {id: 228, argomento: "Aritmie e fibrillazione atriale", domanda: "Su quali score basi la scelta di anticoagulare un paziente con FA non valvolare?", risposta: "CHA2DS2-VASc per il rischio tromboembolico, bilanciato con HAS-BLED per il rischio emorragico."},
  {id: 229, argomento: "Aritmie e fibrillazione atriale", domanda: "Effetti collaterali dell'adenosina.", risposta: "Flushing, dolore toracico, dispnea, breve asistolia/bradicardia; broncospasmo negli asmatici."},
  {id: 230, argomento: "Aritmie e fibrillazione atriale", domanda: "Perché la FA causa embolie?", risposta: "Ristagno ematico nell'auricola sinistra per perdita sistole atriale."},
  {id: 231, argomento: "Aritmie e fibrillazione atriale", domanda: "FA >48 ore: come cardioversione?", risposta: "Anticoagulazione prima o TEE per escludere trombi se cardioversione precoce."},
  {id: 232, argomento: "Aritmie e fibrillazione atriale", domanda: "Anticoagulazione dopo cardioversione: durata minima.", risposta: "Almeno 4 settimane."},
  {id: 233, argomento: "Aritmie e fibrillazione atriale", domanda: "Pill in the pocket: farmaci.", risposta: "Flecainide o propafenone in pazienti senza cardiopatia strutturale."},
  {id: 234, argomento: "Aritmie e fibrillazione atriale", domanda: "Cardioversione farmacologica in cardiopatico.", risposta: "Amiodarone."},
  {id: 235, argomento: "Aritmie e fibrillazione atriale", domanda: "Prima linea TPSV stabile.", risposta: "Manovre vagali, poi adenosina EV in bolo rapido."},
  {id: 236, argomento: "Aritmie e fibrillazione atriale", domanda: "Definizione di storm elettrico.", risposta: "Almeno 3 episodi di TV/FV in 24 ore."},
  {id: 237, argomento: "Aritmie e fibrillazione atriale", domanda: "ADR cronici dell'amiodarone.", risposta: "Disfunzione tiroidea, fibrosi polmonare, epatotossicità, depositi corneali, proaritmia."},

  // --- 16. SCOMPENSO CARDIACO ------------------------------------------
  {id: 238, argomento: "Scompenso cardiaco", domanda: "Terapia dello scompenso per ridurre la mortalità: i quattro pilastri.", risposta: "ACE-i/ARNI (sacubitril-valsartan) + β-bloccante + antialdosteronico + SGLT2-inibitore."},
  {id: 239, argomento: "Scompenso cardiaco", domanda: "Cos'è il sacubitril e quando si usa?", risposta: "Inibitore della neprilisina; associato a valsartan nello scompenso a FE ridotta ancora sintomatico nonostante terapia ottimale."},
  {id: 240, argomento: "Scompenso cardiaco", domanda: "Meccanismo d'azione degli SGLT2-inibitori.", risposta: "Inibiscono il cotrasportatore sodio-glucosio SGLT2 nel tubulo prossimale → glicosuria e natriuresi."},
  {id: 241, argomento: "Scompenso cardiaco", domanda: "Paziente con ginecomastia in terapia per scompenso: quale farmaco sospettare?", risposta: "Spironolattone (sostituire con eplerenone, che dà meno ginecomastia)."},
  {id: 242, argomento: "Scompenso cardiaco", domanda: "Almeno 2 effetti collaterali delle glifozine.", risposta: "Infezioni genito-urinarie, deplezione volemica/ipotensione, chetoacidosi diabetica euglicemica."},
  {id: 243, argomento: "Scompenso cardiaco", domanda: "Qual è il vantaggio del sacubitril/valsartan rispetto al solo ACE-inibitore?", risposta: "Maggiore efficacia nel ridurre mortalità e ospedalizzazioni; agisce anche sulla ritenzione idrica."},
  {id: 244, argomento: "Scompenso cardiaco", domanda: "Quattro pilastri HFrEF.", risposta: "ACE-i/ARNI, beta-bloccante, antialdosteronico, SGLT2-inibitore."},
  {id: 245, argomento: "Scompenso cardiaco", domanda: "Ruolo dei diuretici nello scompenso.", risposta: "Controllo dei sintomi congestizi, senza principale effetto prognostico."},
  {id: 246, argomento: "Scompenso cardiaco", domanda: "Quando non aumentare beta-bloccante?", risposta: "Scompenso acuto instabile o congestione severa non compensata."},
  {id: 247, argomento: "Scompenso cardiaco", domanda: "Cos'è sacubitril?", risposta: "Inibitore della neprilisina associato a valsartan nell'HFrEF sintomatico."},
  {id: 248, argomento: "Scompenso cardiaco", domanda: "ADR spironolattone tipico.", risposta: "Ginecomastia e iperkaliemia."},
  {id: 249, argomento: "Scompenso cardiaco", domanda: "ADR glifozine.", risposta: "Infezioni genito-urinarie, deplezione volemica, chetoacidosi euglicemica."},
  {id: 250, argomento: "Scompenso cardiaco", domanda: "Perché ACE-i/ARB/ARNI migliorano prognosi?", risposta: "Contrastano RAAS e rimodellamento cardiaco."},
  {id: 251, argomento: "Scompenso cardiaco", domanda: "Quando considerare ICD?", risposta: "FE ridotta persistente in pazienti selezionati ad alto rischio di morte improvvisa."},

  // --- 17. IPERTENSIONE ARTERIOSA --------------------------------------
  {id: 252, argomento: "Ipertensione arteriosa", domanda: "Prima linea anti-ipertensiva nel paziente sano senza fattori di rischio.", risposta: "A scelta tra ACE-i/ARB, calcio-antagonista o tiazidico; spesso in associazione (es. ACE-i + calcio-antagonista)."},
  {id: 253, argomento: "Ipertensione arteriosa", domanda: "Farmaco di uso comune che dà tosse cronica.", risposta: "ACE-inibitore (accumulo di bradichinina)."},
  {id: 254, argomento: "Ipertensione arteriosa", domanda: "3 farmaci per la crisi ipertensiva con via di somministrazione.", risposta: "Labetalolo ev, urapidil ev, nitroglicerina/nitroprussiato ev (clonidina, esmololo ev)."},
  {id: 255, argomento: "Ipertensione arteriosa", domanda: "Farmaci antipertensivi controindicati in gravidanza.", risposta: "ACE-inibitori e sartani (e tiazidici sconsigliati)."},
  {id: 256, argomento: "Ipertensione arteriosa", domanda: "Ipertensione resistente: prima linea aggiuntiva.", risposta: "Aggiungere spironolattone (antialdosteronico) al regime di 3 farmaci (ACE-i/ARB + Ca-antagonista + tiazidico)."},
  {id: 257, argomento: "Ipertensione arteriosa", domanda: "Effetti collaterali dei tiazidici.", risposta: "Ipokaliemia, iponatriemia, iperuricemia, iperglicemia, ipercalcemia, disfunzione erettile."},
  {id: 258, argomento: "Ipertensione arteriosa", domanda: "Stenosi dell'arteria renale bilaterale: perché evitare ACE-i e sartani?", risposta: "Bloccano la vasocostrizione dell'arteriola efferente che mantiene la GFR → insufficienza renale acuta."},
  {id: 259, argomento: "Ipertensione arteriosa", domanda: "Perché non si associano mai un ACE-inibitore e un sartano?", risposta: "Perché agiscono sullo stesso sistema (RAAS) senza beneficio aggiuntivo e con maggior rischio di iperkaliemia e danno renale."},
  {id: 260, argomento: "Ipertensione arteriosa", domanda: "Classi di prima linea nell'ipertensione.", risposta: "ACE-i/ARB, calcio-antagonisti, tiazidici; beta-bloccanti se indicazione specifica."},
  {id: 261, argomento: "Ipertensione arteriosa", domanda: "ACE-inibitore: effetto collaterale tipico.", risposta: "Tosse secca da bradichinina."},
  {id: 262, argomento: "Ipertensione arteriosa", domanda: "Controindicazione ACE-i/ARB in gravidanza.", risposta: "Tossicità fetale da blocco RAAS."},
  {id: 263, argomento: "Ipertensione arteriosa", domanda: "Ipertensione resistente: farmaco aggiuntivo.", risposta: "Spironolattone."},
  {id: 264, argomento: "Ipertensione arteriosa", domanda: "ADR tiazidici.", risposta: "Ipokaliemia, iponatriemia, iperuricemia, iperglicemia, ipercalcemia."},
  {id: 265, argomento: "Ipertensione arteriosa", domanda: "Perché evitare ACE-i in stenosi renale bilaterale?", risposta: "Possono ridurre GFR bloccando vasocostrizione efferente."},
  {id: 266, argomento: "Ipertensione arteriosa", domanda: "Crisi ipertensiva con danno d'organo: via terapeutica.", risposta: "Farmaci EV monitorati, es. labetalolo, urapidil, nitroglicerina/nitroprussiato."},
  {id: 267, argomento: "Ipertensione arteriosa", domanda: "Errore nell'urgenza ipertensiva senza danno d'organo.", risposta: "Ridurre troppo rapidamente la pressione."},

  // --- 18. ANTICOAGULANTI E ANTIAGGREGANTI -----------------------------
  {id: 268, argomento: "Anticoagulanti e antiaggreganti", domanda: "Tre indicazioni agli anticoagulanti orali diretti (DOAC).", risposta: "Prevenzione dell'ictus nella FA non valvolare, trattamento di TVP/EP, profilassi del TEV dopo chirurgia ortopedica maggiore."},
  {id: 269, argomento: "Anticoagulanti e antiaggreganti", domanda: "Emorragia attiva grave in paziente in Coumadin (warfarin): cosa fai?", risposta: "Sospendere il farmaco, vitamina K ev e, se grave, concentrato del complesso protrombinico (PCC)."},
  {id: 270, argomento: "Anticoagulanti e antiaggreganti", domanda: "Necrosi cutanea da warfarin: cosa è successo e cosa fai?", risposta: "Calo rapido della proteina C (stato pro-trombotico iniziale). Sospendere warfarin, dare eparina (EBPM) e vitamina K."},
  {id: 271, argomento: "Anticoagulanti e antiaggreganti", domanda: "Qual è il bersaglio del warfarin e come si monitora?", risposta: "Inibisce la sintesi vitamina K-dipendente dei fattori II, VII, IX, X; si monitora con INR (target 2-3)."},
  {id: 272, argomento: "Anticoagulanti e antiaggreganti", domanda: "Cita i bersagli dei DOAC.", risposta: "Dabigatran inibisce la trombina (IIa); rivaroxaban, apixaban ed edoxaban inibiscono il fattore Xa."},
  {id: 273, argomento: "Anticoagulanti e antiaggreganti", domanda: "In quale contesto i DOAC sono controindicati a favore del warfarin?", risposta: "Nella FA valvolare (protesi meccanica/stenosi mitralica) e nella sindrome da anticorpi antifosfolipidi."},
  {id: 274, argomento: "Anticoagulanti e antiaggreganti", domanda: "Dose antiaggregante aspirina.", risposta: "75-100 mg/die."},
  {id: 275, argomento: "Anticoagulanti e antiaggreganti", domanda: "Meccanismo aspirina antiaggregante.", risposta: "Inibizione irreversibile COX piastrinica e TXA2."},
  {id: 276, argomento: "Anticoagulanti e antiaggreganti", domanda: "Bersaglio dabigatran.", risposta: "Trombina/fattore IIa."},
  {id: 277, argomento: "Anticoagulanti e antiaggreganti", domanda: "Bersaglio rivaroxaban/apixaban/edoxaban.", risposta: "Fattore Xa."},
  {id: 278, argomento: "Anticoagulanti e antiaggreganti", domanda: "Antidoto/strategia warfarin in sanguinamento grave.", risposta: "Vitamina K EV e PCC, sospendendo warfarin."},
  {id: 279, argomento: "Anticoagulanti e antiaggreganti", domanda: "Perché necrosi cutanea da warfarin?", risposta: "Calo rapido proteina C con stato protrombotico iniziale."},
  {id: 280, argomento: "Anticoagulanti e antiaggreganti", domanda: "Quando preferire warfarin ai DOAC?", risposta: "Protesi meccanica/stenosi mitralica significativa e sindrome antifosfolipidi."},
  {id: 281, argomento: "Anticoagulanti e antiaggreganti", domanda: "Rischio principale delle terapie antitrombotiche.", risposta: "Sanguinamento."},

  // --- 19. TROMBOEMBOLISMO VENOSO --------------------------------------
  {id: 282, argomento: "Tromboembolismo venoso", domanda: "Durata minima della terapia anticoagulante per una TVP.", risposta: "Almeno 3 mesi (più a lungo se TEV recidivante o fattore di rischio persistente)."},
  {id: 283, argomento: "Tromboembolismo venoso", domanda: "Paziente con EP ad alto rischio (ipoteso, tachicardico): terapia.", risposta: "Trombolisi sistemica (rtPA) + eparina; ECMO/embolectomia se controindicazioni o instabilità refrattaria."},
  {id: 284, argomento: "Tromboembolismo venoso", domanda: "Qual è oggi la terapia di prima scelta nella TVP/EP non complicata?", risposta: "I DOAC, salvo controindicazioni (es. insufficienza renale grave, gravidanza, sindrome da antifosfolipidi)."},
  {id: 285, argomento: "Tromboembolismo venoso", domanda: "TEV comprende quali quadri?", risposta: "TVP ed embolia polmonare."},
  {id: 286, argomento: "Tromboembolismo venoso", domanda: "Sintomi tipici EP.", risposta: "Dispnea improvvisa, dolore pleuritico, tachicardia, ipossiemia o sincope."},
  {id: 287, argomento: "Tromboembolismo venoso", domanda: "Ruolo D-dimero.", risposta: "Esclude TEV se negativo in bassa probabilità clinica; non specifico se positivo."},
  {id: 288, argomento: "Tromboembolismo venoso", domanda: "Imaging di conferma EP.", risposta: "Angio-TC polmonare se non controindicata."},
  {id: 289, argomento: "Tromboembolismo venoso", domanda: "Terapia prima scelta TVP/EP stabile.", risposta: "Anticoagulazione, spesso DOAC se non controindicati."},
  {id: 290, argomento: "Tromboembolismo venoso", domanda: "Durata minima anticoagulante per TVP.", risposta: "Almeno 3 mesi."},
  {id: 291, argomento: "Tromboembolismo venoso", domanda: "Terapia EP ad alto rischio.", risposta: "Trombolisi sistemica + eparina/supporto, salvo controindicazioni."},
  {id: 292, argomento: "Tromboembolismo venoso", domanda: "Quando filtro cavale?", risposta: "Controindicazione assoluta ad anticoagulazione o recidiva nonostante terapia adeguata in casi selezionati."},

  // --- 20. ARTRITE REUMATOIDE ------------------------------------------
  {id: 293, argomento: "Artrite reumatoide", domanda: "Paziente con AR: come imposti la terapia?", risposta: "Metotrexato 15 mg/settimana + acido folico 24 h dopo, con prednisone a basse dosi (bridge) da sospendere entro 6 mesi."},
  {id: 294, argomento: "Artrite reumatoide", domanda: "4 DMARD convenzionali in AR.", risposta: "Metotrexato, sulfasalazina, leflunomide, idrossiclorochina."},
  {id: 295, argomento: "Artrite reumatoide", domanda: "Quale vitamina dare il giorno dopo il metotrexato?", risposta: "Acido folico (folina, vitamina B9)."},
  {id: 296, argomento: "Artrite reumatoide", domanda: "Quale farmaco per AR dà crisi ipertensive, diarrea e cefalea?", risposta: "Leflunomide."},
  {id: 297, argomento: "Artrite reumatoide", domanda: "Donna gravida con nuova diagnosi di AR: cosa dai?", risposta: "Sulfasalazina (e/o idrossiclorochina), compatibili con la gravidanza; metotrexato e leflunomide sono controindicati."},
  {id: 298, argomento: "Artrite reumatoide", domanda: "Esami infettivologici prima di una terapia biologica per AR.", risposta: "Screening per tubercolosi (Quantiferon/Mantoux) ed epatiti B e C (HBV, HCV)."},
  {id: 299, argomento: "Artrite reumatoide", domanda: "Indica 3 anti-TNF.", risposta: "Infliximab, adalimumab, etanercept (anche golimumab, certolizumab pegol)."},
  {id: 300, argomento: "Artrite reumatoide", domanda: "Due anti-IL-6.", risposta: "Tocilizumab e sarilumab."},
  {id: 301, argomento: "Artrite reumatoide", domanda: "Effetto collaterale comune dei JAK-inibitori.", risposta: "Aumentato rischio di infezioni (es. herpes zoster); anche dislipidemia e citopenie."},
  {id: 302, argomento: "Artrite reumatoide", domanda: "Quale farmaco NON associare all'azatioprina e perché?", risposta: "Allopurinolo: inibisce la xantina ossidasi e fa accumulare i metaboliti dell'azatioprina → aplasia midollare."},
  {id: 303, argomento: "Artrite reumatoide", domanda: "Spondiloartrite assiale: terapia di prima e seconda linea.", risposta: "Prima linea: FANS a dose piena e continuativa. Seconda linea: biologici anti-TNF o anti-IL-17 (i DMARD convenzionali sono inefficaci sulla forma assiale)."},
  {id: 304, argomento: "Artrite reumatoide", domanda: "Obiettivo terapeutico AR.", risposta: "Remissione o bassa attività, prevenendo erosioni e disabilità."},
  {id: 305, argomento: "Artrite reumatoide", domanda: "DMARD cardine AR.", risposta: "Metotrexato."},
  {id: 306, argomento: "Artrite reumatoide", domanda: "Dose metotrexato tipica nel file.", risposta: "15 mg/settimana con acido folico 24 ore dopo."},
  {id: 307, argomento: "Artrite reumatoide", domanda: "Perché acido folico con MTX?", risposta: "Riduce tossicità mucosale, epatica ed ematologica."},
  {id: 308, argomento: "Artrite reumatoide", domanda: "DMARD compatibili con gravidanza.", risposta: "Sulfasalazina e idrossiclorochina."},
  {id: 309, argomento: "Artrite reumatoide", domanda: "Screening prima dei biologici.", risposta: "TBC latente, HBV/HCV e rischio infettivo."},
  {id: 310, argomento: "Artrite reumatoide", domanda: "Tre anti-TNF.", risposta: "Infliximab, adalimumab, etanercept."},
  {id: 311, argomento: "Artrite reumatoide", domanda: "ADR JAK-inibitori.", risposta: "Infezioni, herpes zoster, citopenie/dislipidemia e rischio trombotico/cardiovascolare."},

  // --- 21. ARTRITE PSORIASICA ------------------------------------------
  {id: 312, argomento: "Artrite psoriasica", domanda: "Quali domini guidano terapia PsA?", risposta: "Artrite periferica/assiale, entesite, dattilite, cute/unghie, uveite e IBD."},
  {id: 313, argomento: "Artrite psoriasica", domanda: "DMARD convenzionali nella PsA periferica.", risposta: "Metotrexato, leflunomide o sulfasalazina."},
  {id: 314, argomento: "Artrite psoriasica", domanda: "Biologici usati nella PsA.", risposta: "Anti-TNF, anti-IL17, anti-IL23 o anti-IL12/23."},
  {id: 315, argomento: "Artrite psoriasica", domanda: "Farmaco preferibile se PsA con uveite.", risposta: "Anti-TNF."},
  {id: 316, argomento: "Artrite psoriasica", domanda: "Quale classe usare con cautela se IBD?", risposta: "Anti-IL17, perché possono peggiorare/non essere ideali nelle IBD."},
  {id: 317, argomento: "Artrite psoriasica", domanda: "Che cos'è apremilast?", risposta: "Inibitore PDE4 orale con effetto immunomodulante."},
  {id: 318, argomento: "Artrite psoriasica", domanda: "Che cos'è dattilite?", risposta: "Infiammazione diffusa di un dito, tipica della PsA."},
  {id: 319, argomento: "Artrite psoriasica", domanda: "Quando passare a biologico nella PsA?", risposta: "Malattia attiva moderata-severa, domini severi o fallimento/intolleranza ai convenzionali."},

  // --- 22. VASCULITI E POLIMIALGIA -------------------------------------
  {id: 320, argomento: "Vasculiti e polimialgia", domanda: "Quale biologico è utile nell'arterite gigantocellulare e perché?", risposta: "Tocilizumab (anti-IL-6): consente una più rapida e sicura riduzione dello steroide, risparmiando dose cumulativa."},
  {id: 321, argomento: "Vasculiti e polimialgia", domanda: "Polimialgia reumatica con cefalea temporale: imposta la terapia.", risposta: "Sospetta arterite di Horton: glucocorticoidi (prednisone 40-60 mg/die se rischio ischemico) con scalo lento; tocilizumab se necessario."},
  {id: 322, argomento: "Vasculiti e polimialgia", domanda: "Granulomatosi con poliangioite (GPA): prima linea.", risposta: "Prednisone 1 mg/kg/die (o boli di metilprednisolone 500-1000 mg x3 se organi a rischio) + ciclofosfamide o rituximab."},
  {id: 323, argomento: "Vasculiti e polimialgia", domanda: "Classificazione vasculiti per calibro.", risposta: "Grandi, medi, piccoli vasi e forme miste/altre."},
  {id: 324, argomento: "Vasculiti e polimialgia", domanda: "Vasculiti dei grandi vasi citate.", risposta: "Arterite giganto-cellulare e Takayasu."},
  {id: 325, argomento: "Vasculiti e polimialgia", domanda: "Vasculiti ANCA-associate citate.", risposta: "GPA, EGPA e MPA."},
  {id: 326, argomento: "Vasculiti e polimialgia", domanda: "Due fasi terapia vasculiti.", risposta: "Induzione della remissione e mantenimento."},
  {id: 327, argomento: "Vasculiti e polimialgia", domanda: "Complicanza temibile GCA.", risposta: "Perdita visiva/ischemia ottica."},
  {id: 328, argomento: "Vasculiti e polimialgia", domanda: "Terapia iniziale GCA.", risposta: "Glucocorticoidi ad alte dosi, urgenti se sintomi oculari."},
  {id: 329, argomento: "Vasculiti e polimialgia", domanda: "Biologico steroid-sparing nella GCA.", risposta: "Tocilizumab, anti-IL6."},
  {id: 330, argomento: "Vasculiti e polimialgia", domanda: "Associazione da cercare nella polimialgia reumatica.", risposta: "Arterite giganto-cellulare."},

  // --- 23. LES E CONNETTIVITI ------------------------------------------
  {id: 331, argomento: "LES e connettiviti", domanda: "Terapia della nefrite lupica III-IV.", risposta: "Induzione con ciclofosfamide (o micofenolato) + corticosteroide; mantenimento con micofenolato/azatioprina."},
  {id: 332, argomento: "LES e connettiviti", domanda: "Quale farmaco per il LES dà tossicità retinica?", risposta: "Idrossiclorochina (maculopatia: serve monitoraggio oculistico)."},
  {id: 333, argomento: "LES e connettiviti", domanda: "Due farmaci per l'ipertensione polmonare nella sclerosi sistemica.", risposta: "Antagonisti dell'endotelina (bosentan/ambrisentan) e PDE5-inibitori (sildenafil/tadalafil)."},
  {id: 334, argomento: "LES e connettiviti", domanda: "Prima linea nel Raynaud da sclerosi sistemica.", risposta: "Calcio-antagonista diidropiridinico (es. nifedipina/amlodipina)."},
  {id: 335, argomento: "LES e connettiviti", domanda: "Quale farmaco di fondo si usa praticamente in tutti i pazienti con LES?", risposta: "L'idrossiclorochina."},
  {id: 336, argomento: "LES e connettiviti", domanda: "Perché nella sindrome da anticorpi antifosfolipidi si preferisce il warfarin ai DOAC?", risposta: "Perché i DOAC si sono dimostrati meno efficaci nel prevenire le recidive trombotiche in questa sindrome."},
  {id: 337, argomento: "LES e connettiviti", domanda: "Farmaco di fondo quasi universale nel LES.", risposta: "Idrossiclorochina."},
  {id: 338, argomento: "LES e connettiviti", domanda: "Tossicità idrossiclorochina.", risposta: "Retinopatia/maculopatia, da monitorare con controlli oculistici."},
  {id: 339, argomento: "LES e connettiviti", domanda: "Definizione remissione LES nella dispensa.", risposta: "SLEDAI 0, idrossiclorochina e prednisone ≤5 mg/die."},
  {id: 340, argomento: "LES e connettiviti", domanda: "Perché fotoprotezione nel LES?", risposta: "UV stimolano la malattia, soprattutto cutanea; SPF almeno 30."},
  {id: 341, argomento: "LES e connettiviti", domanda: "Nefrite lupica III-IV: terapia.", risposta: "Induzione con ciclofosfamide o micofenolato + corticosteroide; mantenimento con micofenolato/azatioprina."},
  {id: 342, argomento: "LES e connettiviti", domanda: "Target belimumab.", risposta: "BAFF/BLyS."},
  {id: 343, argomento: "LES e connettiviti", domanda: "Target anifrolumab.", risposta: "Recettore interferone di tipo I."},
  {id: 344, argomento: "LES e connettiviti", domanda: "Raynaud da sclerosi sistemica: prima linea.", risposta: "Calcio-antagonista diidropiridinico, es. nifedipina/amlodipina."},

  // --- 24. MALATTIE INFIAMMATORIE INTESTINALI --------------------------
  {id: 345, argomento: "Malattie infiammatorie intestinali", domanda: "RCU lieve-moderata: terapia.", risposta: "Mesalazina orale 2,4-4,8 g/die + mesalazina topica (supposte/clismi)."},
  {id: 346, argomento: "Malattie infiammatorie intestinali", domanda: "RCU cortico-resistente: quale immunosoppressore prima dei biologici?", risposta: "Azatioprina (o 6-mercaptopurina)."},
  {id: 347, argomento: "Malattie infiammatorie intestinali", domanda: "RCU severa che non risponde ad azatioprina, paziente vuole solo terapia orale.", risposta: "JAK-inibitore orale (tofacitinib/upadacitinib)."},
  {id: 348, argomento: "Malattie infiammatorie intestinali", domanda: "Almeno 4 biologici approvati EMA per IBD.", risposta: "Infliximab, adalimumab, golimumab, vedolizumab (anche ustekinumab)."},
  {id: 349, argomento: "Malattie infiammatorie intestinali", domanda: "Cos'è vedolizumab e per cosa si usa?", risposta: "Anticorpo anti-integrina α4β7 (selettivo per l'intestino); RCU e Crohn."},
  {id: 350, argomento: "Malattie infiammatorie intestinali", domanda: "Crohn con sclerosi multipla: quale biologico?", risposta: "Vedolizumab (gut-selettivo); evitare gli anti-TNF, che possono peggiorare la demielinizzazione."},
  {id: 351, argomento: "Malattie infiammatorie intestinali", domanda: "Quali classi di farmaci si usano per indurre e mantenere la remissione nelle IBD moderate-gravi?", risposta: "Corticosteroidi per l'induzione; immunosoppressori (azatioprina) e biologici (anti-TNF) per il mantenimento."},
  {id: 352, argomento: "Malattie infiammatorie intestinali", domanda: "Principali IBD.", risposta: "Colite ulcerosa e malattia di Crohn."},
  {id: 353, argomento: "Malattie infiammatorie intestinali", domanda: "Obiettivi moderni nelle IBD.", risposta: "Remissione clinica, normalizzazione esami e guarigione mucosale/endoscopica."},
  {id: 354, argomento: "Malattie infiammatorie intestinali", domanda: "Score CU e Crohn.", risposta: "Mayo per colite ulcerosa; CDAI per Crohn."},
  {id: 355, argomento: "Malattie infiammatorie intestinali", domanda: "Terapia RCU lieve-moderata.", risposta: "Mesalazina orale 2,4-4,8 g/die + mesalazina topica."},
  {id: 356, argomento: "Malattie infiammatorie intestinali", domanda: "Definizione steroido-dipendenza.", risposta: "Recidiva durante decalage/poco dopo sospensione o ≥2 cicli steroide/anno."},
  {id: 357, argomento: "Malattie infiammatorie intestinali", domanda: "Biologico gut-selettivo.", risposta: "Vedolizumab, anti-integrina α4β7."},
  {id: 358, argomento: "Malattie infiammatorie intestinali", domanda: "Perché azatioprina con anti-TNF?", risposta: "Riduce immunogenicità e aiuta mantenimento."},
  {id: 359, argomento: "Malattie infiammatorie intestinali", domanda: "Crohn con sclerosi multipla: biologico preferito.", risposta: "Vedolizumab; evitare anti-TNF per rischio demielinizzazione."},

  // --- 25. GERD E H. PYLORI --------------------------------------------
  {id: 360, argomento: "GERD e H. pylori", domanda: "Almeno 3 effetti collaterali degli inibitori di pompa (PPI).", risposta: "Infezioni enteriche (C. difficile), malassorbimento di B12/Mg/calcio/ferro, polmonite, danno renale, ipergastrinemia."},
  {id: 361, argomento: "GERD e H. pylori", domanda: "Prima linea per H. pylori in Italia.", risposta: "Terapia quadruplice con bismuto (PPI + bismuto + tetraciclina + metronidazolo = Pylera) per 10-14 gg."},
  {id: 362, argomento: "GERD e H. pylori", domanda: "GERD non complicato: terapia.", risposta: "PPI a dose singola (es. pantoprazolo 40 mg) prima dei pasti per 4-8 settimane + stile di vita."},
  {id: 363, argomento: "GERD e H. pylori", domanda: "Inibitori dell'acidità di nuova classe (PCAB): cosa sono?", risposta: "Vonoprazan (revaprazan): bloccanti competitivi del potassio sulla pompa protonica."},
  {id: 364, argomento: "GERD e H. pylori", domanda: "Equivalenze tra PPI.", risposta: "Omeprazolo 20 mg ≈ pantoprazolo 40 mg ≈ lansoprazolo 30 mg ≈ esomeprazolo 40 mg ≈ rabeprazolo 20 mg."},
  {id: 365, argomento: "GERD e H. pylori", domanda: "Meccanismo PPI.", risposta: "Inibizione irreversibile della pompa H+/K+ ATPasi parietale."},
  {id: 366, argomento: "GERD e H. pylori", domanda: "Quando assumere PPI?", risposta: "Prima del pasto, per colpire pompe attivate."},
  {id: 367, argomento: "GERD e H. pylori", domanda: "Equivalenza omeprazolo-pantoprazolo.", risposta: "Omeprazolo 20 mg ≈ pantoprazolo 40 mg."},
  {id: 368, argomento: "GERD e H. pylori", domanda: "Prima linea H. pylori in Italia.", risposta: "Quadruplice con bismuto: PPI + bismuto + tetraciclina + metronidazolo per 10-14 giorni."},
  {id: 369, argomento: "GERD e H. pylori", domanda: "Perché non monoterapia antibiotica in H. pylori?", risposta: "Alto rischio di fallimento e resistenze."},
  {id: 370, argomento: "GERD e H. pylori", domanda: "Cosa sono i PCAB?", risposta: "Bloccanti competitivi del potassio sulla pompa protonica, es. vonoprazan."},
  {id: 371, argomento: "GERD e H. pylori", domanda: "ADR dei PPI a lungo termine.", risposta: "C. difficile, malassorbimento B12/Mg/calcio/ferro, polmonite, danno renale."},

  // --- 26. PANCREATITE -------------------------------------------------
  {id: 372, argomento: "Pancreatite", domanda: "Idratazione nella pancreatite acuta: quale liquido?", risposta: "Ringer lattato, con idratazione moderata (non aggressiva), titolata sul paziente."},
  {id: 373, argomento: "Pancreatite", domanda: "Due cause più frequenti di pancreatite acuta.", risposta: "Calcoli biliari e alcol."},
  {id: 374, argomento: "Pancreatite", domanda: "Farmaco principale della pancreatite autoimmune.", risposta: "Corticosteroide (prednisone 0,5-1 mg/kg/die) con scalo lento."},
  {id: 375, argomento: "Pancreatite", domanda: "Regola diagnostica pancreatite acuta.", risposta: "2 su 3: dolore tipico, lipasi/amilasi >3x, imaging compatibile."},
  {id: 376, argomento: "Pancreatite", domanda: "Dolore tipico pancreatite.", risposta: "Epigastrico a barra, irradiato posteriormente."},
  {id: 377, argomento: "Pancreatite", domanda: "Tre pilastri supporto pancreatite acuta.", risposta: "Idratazione, analgesia e nutrizione."},
  {id: 378, argomento: "Pancreatite", domanda: "Liquido preferito nell'idratazione.", risposta: "Ringer lattato, con idratazione moderata titolata."},
  {id: 379, argomento: "Pancreatite", domanda: "Antibiotici in pancreatite acuta: quando?", risposta: "Non routinari; solo infezione documentata/sospetta o necrosi infetta."},
  {id: 380, argomento: "Pancreatite", domanda: "Due cause più frequenti.", risposta: "Calcoli biliari e alcol."},
  {id: 381, argomento: "Pancreatite", domanda: "Farmaco pancreatite autoimmune.", risposta: "Prednisone 0,5-1 mg/kg/die con scalo lento."},
  {id: 382, argomento: "Pancreatite", domanda: "Perché nutrizione enterale?", risposta: "Mantiene barriera intestinale e riduce complicanze infettive rispetto alla parenterale."},

  // --- 27. CIRROSI EPATICA ---------------------------------------------
  {id: 383, argomento: "Cirrosi epatica", domanda: "Ascite di grado 2 di nuova diagnosi: quale diuretico e dosaggio?", risposta: "Spironolattone 100 mg/die (titolabile fino a 400 mg), ± furosemide."},
  {id: 384, argomento: "Cirrosi epatica", domanda: "Prima azione in paziente con cirrosi e ascite di grado 3.", risposta: "Paracentesi evacuativa con infusione di albumina (≈8 g per litro rimosso oltre i 5 L)."},
  {id: 385, argomento: "Cirrosi epatica", domanda: "Terapia dell'encefalopatia porto-sistemica.", risposta: "Trattare i fattori precipitanti + lattulosio (acidificazione del colon) + rifaximina; aminoacidi ramificati se refrattaria."},
  {id: 386, argomento: "Cirrosi epatica", domanda: "Classe di antibiotici per la peritonite batterica spontanea (PBS).", risposta: "Cefalosporine di 3ª generazione (es. cefotaxime/ceftriaxone) o piperacillina-tazobactam."},
  {id: 387, argomento: "Cirrosi epatica", domanda: "Due farmaci per la profilassi del sanguinamento delle varici esofagee.", risposta: "β-bloccante non selettivo (propranololo o carvedilolo); in alternativa legatura endoscopica."},
  {id: 388, argomento: "Cirrosi epatica", domanda: "Sopravvivenza compensata vs scompensata.", risposta: "Circa 12 anni vs circa 2 anni."},
  {id: 389, argomento: "Cirrosi epatica", domanda: "Probabilità annua di scompenso.", risposta: "5-7%/anno."},
  {id: 390, argomento: "Cirrosi epatica", domanda: "Cos'è ACLF?", risposta: "Scompenso acuto su cirrosi con almeno una organ failure."},
  {id: 391, argomento: "Cirrosi epatica", domanda: "Ascite grado 2: diuretico iniziale.", risposta: "Spironolattone 100 mg/die, titolabile, ± furosemide."},
  {id: 392, argomento: "Cirrosi epatica", domanda: "Ascite grado 3: prima azione.", risposta: "Paracentesi evacuativa + albumina circa 8 g/L oltre i 5 L rimossi."},
  {id: 393, argomento: "Cirrosi epatica", domanda: "Encefalopatia epatica: terapia.", risposta: "Correggere precipitanti + lattulosio + rifaximina."},
  {id: 394, argomento: "Cirrosi epatica", domanda: "PBS: antibiotici.", risposta: "Cefalosporina di 3ª generazione, es. cefotaxime/ceftriaxone, o pip-tazo."},
  {id: 395, argomento: "Cirrosi epatica", domanda: "Profilassi sanguinamento varici.", risposta: "Beta-bloccante non selettivo, es. propranololo/carvedilolo, o legatura endoscopica."},

  // --- 28. DISFUNZIONI TIROIDEE ----------------------------------------
  {id: 396, argomento: "Disfunzioni tiroidee", domanda: "Due farmaci che causano ipotiroidismo.", risposta: "Amiodarone e litio."},
  {id: 397, argomento: "Disfunzioni tiroidee", domanda: "Terapia della tireotossicosi grave da amiodarone.", risposta: "Tionamidi (metimazolo) + corticosteroide (per la forma tipo 2 distruttiva)."},
  {id: 398, argomento: "Disfunzioni tiroidee", domanda: "In quali condizioni tiroidee usi l'integrazione di selenio?", risposta: "Tiroidite di Hashimoto/autoimmune e ipotiroidismo subclinico (e orbitopatia di Basedow lieve)."},
  {id: 399, argomento: "Disfunzioni tiroidee", domanda: "In quali condizioni è necessario aumentare la dose di L-tiroxina?", risposta: "Gravidanza, malassorbimento (celiachia), farmaci che ne riducono l'assorbimento (PPI, ferro, calcio)."},
  {id: 400, argomento: "Disfunzioni tiroidee", domanda: "Qual è il tireostatico di prima scelta nell'ipertiroidismo e perché?", risposta: "Il metimazolo, per durata d'azione maggiore, effetto rapido e minori effetti collaterali rispetto al propiltiouracile."},
  {id: 401, argomento: "Disfunzioni tiroidee", domanda: "Terapia ipotiroidismo.", risposta: "Levotiroxina titolata su TSH e clinica."},
  {id: 402, argomento: "Disfunzioni tiroidee", domanda: "Come assumere levotiroxina?", risposta: "A digiuno, separata da ferro, calcio, PPI/antiacidi e cibo."},
  {id: 403, argomento: "Disfunzioni tiroidee", domanda: "Farmaci che causano ipotiroidismo.", risposta: "Amiodarone e litio."},
  {id: 404, argomento: "Disfunzioni tiroidee", domanda: "Tireostatico di prima scelta.", risposta: "Metimazolo/tiamazolo."},
  {id: 405, argomento: "Disfunzioni tiroidee", domanda: "ADR grave antitiroidei.", risposta: "Agranulocitosi: sospettare con febbre e faringodinia."},
  {id: 406, argomento: "Disfunzioni tiroidee", domanda: "Antitiroideo preferito nel primo trimestre.", risposta: "Propiltiouracile."},
  {id: 407, argomento: "Disfunzioni tiroidee", domanda: "Tireotossicosi grave da amiodarone.", risposta: "Tionamide + corticosteroide se componente distruttiva."},
  {id: 408, argomento: "Disfunzioni tiroidee", domanda: "Ruolo beta-bloccanti nell'ipertiroidismo.", risposta: "Controllano tachicardia, tremore, palpitazioni e sintomi adrenergici."},

  // --- 29. DIABETE MELLITO TIPO 2 --------------------------------------
  {id: 409, argomento: "Diabete mellito tipo 2", domanda: "Iperglicemia che non migliora con lo stile di vita: cosa dai?", risposta: "Metformina (prima linea)."},
  {id: 410, argomento: "Diabete mellito tipo 2", domanda: "Meccanismo delle glifozine (SGLT2-inibitori).", risposta: "Inibiscono il cotrasportatore SGLT2 nel tubulo prossimale → glicosuria, calo ponderale e natriuresi."},
  {id: 411, argomento: "Diabete mellito tipo 2", domanda: "Meccanismo d'azione delle sulfaniluree.", risposta: "Bloccano i canali del potassio ATP-dipendenti della β-cellula → depolarizzazione e rilascio di insulina."},
  {id: 412, argomento: "Diabete mellito tipo 2", domanda: "Chetoacidosi diabetica con K normale: cosa fai per il potassio?", risposta: "Aggiungere KCl ai liquidi (10-20 mEq/h) prima/durante l'insulina, perché l'insulina lo farà scendere; monitorare K ed ECG."},
  {id: 413, argomento: "Diabete mellito tipo 2", domanda: "Paziente con metformina che deve fare TC con contrasto: cosa è importante?", risposta: "Sospendere la metformina (rischio di acidosi lattica con il mezzo di contrasto/danno renale)."},
  {id: 414, argomento: "Diabete mellito tipo 2", domanda: "Quale classe preferisci nel diabetico con scompenso cardiaco o malattia renale cronica e perché?", risposta: "Gli SGLT2-inibitori (gliflozine), per il beneficio cardio-renale dimostrato."},
  {id: 415, argomento: "Diabete mellito tipo 2", domanda: "Quale classe associa controllo glicemico e calo ponderale con beneficio cardiovascolare?", risposta: "Gli agonisti del GLP-1 (es. semaglutide, liraglutide)."},
  {id: 416, argomento: "Diabete mellito tipo 2", domanda: "Prima linea farmacologica T2D.", risposta: "Metformina, se non controindicata, con stile di vita."},
  {id: 417, argomento: "Diabete mellito tipo 2", domanda: "Meccanismo metformina.", risposta: "Riduce produzione epatica di glucosio e migliora sensibilità insulinica."},
  {id: 418, argomento: "Diabete mellito tipo 2", domanda: "ADR comune metformina.", risposta: "Disturbi gastrointestinali."},
  {id: 419, argomento: "Diabete mellito tipo 2", domanda: "Rischio raro metformina.", risposta: "Acidosi lattica, soprattutto in IRC severa/condizioni ipossiche."},
  {id: 420, argomento: "Diabete mellito tipo 2", domanda: "Meccanismo SGLT2-inibitori.", risposta: "Blocco riassorbimento glucosio nel tubulo prossimale con glicosuria."},
  {id: 421, argomento: "Diabete mellito tipo 2", domanda: "Classe utile in diabete con scompenso/CKD.", risposta: "SGLT2-inibitori per beneficio cardio-renale."},
  {id: 422, argomento: "Diabete mellito tipo 2", domanda: "Classe con calo ponderale e beneficio CV.", risposta: "Agonisti GLP-1, es. semaglutide/liraglutide."},
  {id: 423, argomento: "Diabete mellito tipo 2", domanda: "Principale rischio insulina.", risposta: "Ipoglicemia e aumento di peso."},

  // --- 30. OSTEOPOROSI -------------------------------------------------
  {id: 424, argomento: "Osteoporosi", domanda: "Almeno due bisfosfonati orali.", risposta: "Alendronato, risedronato, ibandronato."},
  {id: 425, argomento: "Osteoporosi", domanda: "Come si somministra l'alendronato?", risposta: "1 volta/settimana, al mattino a digiuno con acqua povera di calcio; restare in piedi 30 min, non assumere cibo/farmaci per 30-60 min."},
  {id: 426, argomento: "Osteoporosi", domanda: "Denosumab: meccanismo e indicazione.", risposta: "Anticorpo anti-RANKL che blocca gli osteoclasti; osteoporosi (prevenzione di fratture) e metastasi ossee."},
  {id: 427, argomento: "Osteoporosi", domanda: "Farmaco per osteoporosi che, se sospeso bruscamente, dà il maggior rischio di frattura.", risposta: "Denosumab (rebound; va seguito da un bisfosfonato)."},
  {id: 428, argomento: "Osteoporosi", domanda: "Farmaco anabolico puro per l'osteoporosi.", risposta: "Teriparatide (analogo del PTH)."},
  {id: 429, argomento: "Osteoporosi", domanda: "Con quale dose/durata di steroide vanno dati i bisfosfonati?", risposta: "Se prednisone ≥5-7,5 mg/die (o equivalente) per ≥3 mesi."},
  {id: 430, argomento: "Osteoporosi", domanda: "Definizione osteoporosi.", risposta: "Riduzione massa ossea e danno microarchitetturale con fragilità e rischio fratture."},
  {id: 431, argomento: "Osteoporosi", domanda: "Pathway osteoclastico.", risposta: "RANK-RANKL."},
  {id: 432, argomento: "Osteoporosi", domanda: "Meccanismo bisfosfonati.", risposta: "Inibizione riassorbimento osseo mediato dagli osteoclasti."},
  {id: 433, argomento: "Osteoporosi", domanda: "Come assumere alendronato.", risposta: "Una volta/settimana al mattino a digiuno con acqua, restando in piedi 30 min."},
  {id: 434, argomento: "Osteoporosi", domanda: "Target denosumab.", risposta: "RANKL."},
  {id: 435, argomento: "Osteoporosi", domanda: "Rischio sospensione brusca denosumab.", risposta: "Rebound con aumento rischio fratture; va seguito da bisfosfonato."},
  {id: 436, argomento: "Osteoporosi", domanda: "Farmaco anabolico puro.", risposta: "Teriparatide."},
  {id: 437, argomento: "Osteoporosi", domanda: "Quando profilassi osteoporosi da steroide?", risposta: "Prednisone ≥5-7,5 mg/die per ≥3 mesi."},

  // --- 31. NEFROLOGIA E IRC --------------------------------------------
  {id: 438, argomento: "Nefrologia e IRC", domanda: "2 farmaci per l'iperfosfatemia nell'IRC.", risposta: "Chelanti del fosforo: sevelamer (resina) e carbonato/acetato di calcio (o carbonato di lantanio)."},
  {id: 439, argomento: "Nefrologia e IRC", domanda: "Terapia dell'iperkaliemia severa con alterazioni ECG.", risposta: "Calcio gluconato ev subito, poi insulina + glucosata (e β2-agonisti); rimozione con resine/diuretici o dialisi."},
  {id: 440, argomento: "Nefrologia e IRC", domanda: "Almeno 3 indicazioni alla dialisi d'urgenza.", risposta: "Iperkaliemia refrattaria (>6,5), acidosi metabolica severa, sovraccarico di fluidi refrattario, uremia sintomatica (pericardite/encefalopatia)."},
  {id: 441, argomento: "Nefrologia e IRC", domanda: "IRC grave con Hb 9,5: 2 trattamenti fondamentali.", risposta: "Ferro (preferibilmente ev) ed eritropoietina ricombinante (target Hb 10,5-11,5)."},
  {id: 442, argomento: "Nefrologia e IRC", domanda: "Quali due classi di farmaci rallentano la progressione della MRC con proteinuria?", risposta: "ACE-inibitori/sartani (riducono la proteinuria) e SGLT2-inibitori (nefroprotezione)."},
  {id: 443, argomento: "Nefrologia e IRC", domanda: "Differenza AKI/CKD.", risposta: "AKI acuta potenzialmente reversibile; CKD cronica persistente e progressiva."},
  {id: 444, argomento: "Nefrologia e IRC", domanda: "Primo obiettivo in AKI.", risposta: "Identificare/correggere causa, mantenere perfusione ed evitare nefrotossici."},
  {id: 445, argomento: "Nefrologia e IRC", domanda: "Ammine in AKI ipotensiva refrattaria a fluidi.", risposta: "Noradrenalina se servono vasopressori."},
  {id: 446, argomento: "Nefrologia e IRC", domanda: "Ruolo diuretici in AKI.", risposta: "Gestire sovraccarico, non recuperare direttamente funzione renale."},
  {id: 447, argomento: "Nefrologia e IRC", domanda: "Indicazioni dialisi urgente.", risposta: "IperK refrattaria, acidosi severa, sovraccarico refrattario, uremia sintomatica/intossicazioni."},
  {id: 448, argomento: "Nefrologia e IRC", domanda: "Chelanti fosforo in IRC.", risposta: "Sevelamer e carbonato/acetato di calcio, o lantanio."},
  {id: 449, argomento: "Nefrologia e IRC", domanda: "Terapia iperK con ECG alterato.", risposta: "Calcio gluconato EV, poi insulina-glucosio ± beta2 agonista e rimozione K."},
  {id: 450, argomento: "Nefrologia e IRC", domanda: "Classi nefroprotettive in CKD proteinurica.", risposta: "ACE-i/ARB e SGLT2-inibitori."},

  // --- 32. IPB E DISFUNZIONE ERETTILE ----------------------------------
  {id: 451, argomento: "IPB e disfunzione erettile", domanda: "2 farmaci per l'IPB.", risposta: "α-litico (tamsulosina/silodosina) e inibitore 5-α-reduttasi (finasteride/dutasteride)."},
  {id: 452, argomento: "IPB e disfunzione erettile", domanda: "Effetti collaterali degli α-litici.", risposta: "Ipotensione ortostatica, congestione nasale, aneiaculazione, sincope, IFIS (sindrome dell'iride a bandiera)."},
  {id: 453, argomento: "IPB e disfunzione erettile", domanda: "Controindicazioni assolute ai PDE5-inibitori.", risposta: "Uso di nitrati/donatori di NO, retinite pigmentosa, intolleranza al farmaco."},
  {id: 454, argomento: "IPB e disfunzione erettile", domanda: "Qual è il meccanismo degli inibitori della PDE5 nella disfunzione erettile e una controindicazione assoluta?", risposta: "Aumentano il GMP ciclico favorendo l'erezione; controindicati con i nitrati per il rischio di grave ipotensione."},
  {id: 455, argomento: "IPB e disfunzione erettile", domanda: "Cosa sono LUTS?", risposta: "Sintomi del basso tratto urinario, non sempre dovuti alla prostata."},
  {id: 456, argomento: "IPB e disfunzione erettile", domanda: "Sintomi di riempimento LUTS.", risposta: "Urgenza, pollachiuria, nicturia, incontinenza da urgenza."},
  {id: 457, argomento: "IPB e disfunzione erettile", domanda: "Sintomi di svuotamento LUTS.", risposta: "Getto debole, esitazione, mitto intermittente, sforzo, svuotamento incompleto."},
  {id: 458, argomento: "IPB e disfunzione erettile", domanda: "Farmaci IPB.", risposta: "Alfa-litici come tamsulosina/silodosina e 5-ARI come finasteride/dutasteride."},
  {id: 459, argomento: "IPB e disfunzione erettile", domanda: "ADR alfa-litici.", risposta: "Ipotensione ortostatica, congestione nasale, aneiaculazione, sincope, IFIS."},
  {id: 460, argomento: "IPB e disfunzione erettile", domanda: "Meccanismo 5-ARI.", risposta: "Inibiscono conversione testosterone in DHT, riducendo volume prostatico nel tempo."},
  {id: 461, argomento: "IPB e disfunzione erettile", domanda: "Meccanismo PDE5-inibitori.", risposta: "Aumentano cGMP nei corpi cavernosi favorendo erezione."},
  {id: 462, argomento: "IPB e disfunzione erettile", domanda: "Controindicazione assoluta PDE5-inibitori.", risposta: "Nitrati/donatori NO per rischio grave ipotensione."},

  // --- 33. COMPLICANZE TERAPIA ANTITUMORALE ----------------------------
  {id: 463, argomento: "Complicanze terapia antitumorale", domanda: "Neutropenia febbrile: terapia empirica.", risposta: "Monoterapia con piperacillina-tazobactam (o cefepime/ceftazidime o carbapenemico) entro 1 h."},
  {id: 464, argomento: "Complicanze terapia antitumorale", domanda: "Neutropenia febbrile con persistenza/Gram+: cosa aggiungi?", risposta: "Vancomicina (es. piperacillina-tazobactam + vancomicina)."},
  {id: 465, argomento: "Complicanze terapia antitumorale", domanda: "Terapia per la prevenzione dell'iperuricemia da lisi tumorale.", risposta: "Idratazione + allopurinolo (prevenzione); rasburicase se iperuricemia già presente/alto rischio."},
  {id: 466, argomento: "Complicanze terapia antitumorale", domanda: "Paziente in pembrolizumab con miocardite immuno-relata: come tratti?", risposta: "Sospendere l'immunoterapia e dare alte dosi di corticosteroidi."},
  {id: 467, argomento: "Complicanze terapia antitumorale", domanda: "Neutropenia febbrile: che cos'è?", risposta: "Febbre in paziente neutropenico: emergenza infettivologica."},
  {id: 468, argomento: "Complicanze terapia antitumorale", domanda: "Terapia empirica neutropenia febbrile.", risposta: "Piperacillina-tazobactam o cefepime/ceftazidime/carbapenemico entro 1 ora."},
  {id: 469, argomento: "Complicanze terapia antitumorale", domanda: "Quando aggiungere vancomicina?", risposta: "Persistenza febbre, sospetto Gram+, catetere, cute/tessuti molli o instabilità selezionata."},
  {id: 470, argomento: "Complicanze terapia antitumorale", domanda: "Prevenzione lisi tumorale.", risposta: "Idratazione + allopurinolo; rasburicase se alto rischio/iperuricemia."},
  {id: 471, argomento: "Complicanze terapia antitumorale", domanda: "Alterazioni lisi tumorale.", risposta: "Iperuricemia, iperK, iperfosfatemia, ipocalcemia, AKI."},
  {id: 472, argomento: "Complicanze terapia antitumorale", domanda: "Tossicità immuno-relata moderata-severa.", risposta: "Sospendere immunoterapia e dare glucocorticoidi sistemici."},
  {id: 473, argomento: "Complicanze terapia antitumorale", domanda: "Miocardite da pembrolizumab: trattamento.", risposta: "Sospendere immunoterapia e corticosteroidi ad alte dosi."},
  {id: 474, argomento: "Complicanze terapia antitumorale", domanda: "Rischio della mucosite severa.", risposta: "Dolore, disidratazione, malnutrizione e porta d'ingresso infettiva."},

  // --- 34. INSONNIA ----------------------------------------------------
  {id: 475, argomento: "Insonnia", domanda: "Lemborexant: cos'è e dove si usa?", risposta: "Antagonista duale dei recettori dell'orexina (DORA); insonnia da inizio e mantenimento."},
  {id: 476, argomento: "Insonnia", domanda: "Trattamento della sindrome delle gambe senza riposo.", risposta: "Agonisti dopaminergici (pramipexolo/ropinirolo) o gabapentinoidi; clonazepam la sera nelle forme lievi."},
  {id: 477, argomento: "Insonnia", domanda: "Perché le benzodiazepine non sono ideali per l'insonnia cronica nell'anziano?", risposta: "Per rischio di tolleranza, dipendenza, cadute e deterioramento cognitivo; si preferiscono igiene del sonno e Z-drugs a breve termine."},
  {id: 478, argomento: "Insonnia", domanda: "Principio iniziale terapia insonnia.", risposta: "Valutare cause, igiene del sonno e interventi comportamentali."},
  {id: 479, argomento: "Insonnia", domanda: "Perché evitare ipnotici cronici nell'anziano?", risposta: "Rischio tolleranza, dipendenza, cadute e deterioramento cognitivo."},
  {id: 480, argomento: "Insonnia", domanda: "Che cos'è lemborexant?", risposta: "Antagonista duale recettori orexina, per insonnia da inizio e mantenimento."},
  {id: 481, argomento: "Insonnia", domanda: "Terapia restless legs.", risposta: "Agonisti dopaminergici o gabapentinoidi; clonazepam serale nelle forme lievi."},
  {id: 482, argomento: "Insonnia", domanda: "Rischio sospensione brusca ipnotici.", risposta: "Insonnia rebound, ansia e astinenza."},
  {id: 483, argomento: "Insonnia", domanda: "Misure igiene del sonno.", risposta: "Orari regolari, evitare stimolanti/alcol serale, ridurre schermi, ambiente adeguato."},
  {id: 484, argomento: "Insonnia", domanda: "Perché cercare OSAS?", risposta: "Può causare sonno frammentato e richiede terapia specifica."},
  {id: 485, argomento: "Insonnia", domanda: "Obiettivo realistico terapia insonnia.", risposta: "Migliorare qualità/continuità del sonno e funzionamento diurno."},

  // --- 35. ANTIEMETICI E FARMACI GI ------------------------------------
  {id: 486, argomento: "Antiemetici e farmaci GI", domanda: "Terapia antiemetica nel paziente con chemioterapia con cisplatino.", risposta: "Setrone (ondansetron) + desametasone ± antagonista NK1 (aprepitant)."},
  {id: 487, argomento: "Antiemetici e farmaci GI", domanda: "Effetti collaterali della metoclopramide.", risposta: "Sintomi extrapiramidali (distonia, parkinsonismo), iperprolattinemia, sonnolenza."},
  {id: 488, argomento: "Antiemetici e farmaci GI", domanda: "Paziente 75 anni in metoclopramide che sviluppa rigidità e amimia: cosa è successo?", risposta: "Parkinsonismo iatrogeno (sindrome extrapiramidale da metoclopramide); sospendere il farmaco."},
  {id: 489, argomento: "Antiemetici e farmaci GI", domanda: "Due lassativi osmotici.", risposta: "Lattulosio e macrogol (PEG/Movicol)."},

  // --- 36. IPERCALCEMIA PARANEOPLASTICA --------------------------------
  {id: 490, argomento: "Ipercalcemia paraneoplastica", domanda: "Prima linea nell'ipercalcemia (oltre all'idratazione).", risposta: "Bisfosfonati ev (zoledronato); calcitonina per un effetto rapido; denosumab se refrattaria."},
  {id: 491, argomento: "Ipercalcemia paraneoplastica", domanda: "Paziente con K polmone, metastasi ossee, dolore, ipercalcemia: trattamento.", risposta: "Idratazione ± furosemide + bisfosfonato ev; calcitonina e steroide se severa; bisfosfonati anche per il dolore osseo."},

  // --- 37. MISCELLANEA -------------------------------------------------
  {id: 492, argomento: "Miscellanea", domanda: "Principio attivo usato da 3000 anni come anti-infiammatorio.", risposta: "Colchicina."},
  {id: 493, argomento: "Miscellanea", domanda: "Dose minima di corticosteroidi che non dà effetti collaterali a lungo termine.", risposta: "≤7,5 mg/die di prednisone (o equivalente)."},
  {id: 494, argomento: "Miscellanea", domanda: "2 farmaci ipouricemizzanti.", risposta: "Allopurinolo e febuxostat (inibitori della xantina ossidasi)."},
  {id: 495, argomento: "Miscellanea", domanda: "Salbutamolo: classe e uso.", risposta: "β2-agonista a breve durata (SABA); broncodilatatore nell'asma/BPCO."},
  {id: 496, argomento: "Miscellanea", domanda: "Cosa dai in gravidanza per il reflusso?", risposta: "Antiacidi/alginati (es. Gaviscon); sucralfato; PPI (omeprazolo) se necessario, considerati sicuri."},

  // --- 38. FEBBRE E ANTIPIRETICI ---------------------------------------
  {id: 497, argomento: "Febbre e antipiretici", domanda: "Scenario clinico rapido su Febbre e antipiretici: quale principio terapeutico generale va applicato?", risposta: "Identificare gravità, indicazione specifica, controindicazioni e scegliere farmaco/dose coerenti con la dispensa."},

  // --- 39. TERAPIA DEL DOLORE ------------------------------------------
  {id: 498, argomento: "Terapia del dolore", domanda: "Scenario clinico rapido su Terapia del dolore: quale principio terapeutico generale va applicato?", risposta: "Identificare gravità, indicazione specifica, controindicazioni e scegliere farmaco/dose coerenti con la dispensa."},

  // --- 40. INFEZIONI VIE AEREE SUPERIORI -------------------------------
  {id: 499, argomento: "Infezioni vie aeree superiori", domanda: "Scenario clinico rapido su Infezioni vie aeree superiori: quale principio terapeutico generale va applicato?", risposta: "Identificare gravità, indicazione specifica, controindicazioni e scegliere farmaco/dose coerenti con la dispensa."},

  // --- 41. INFLUENZA ---------------------------------------------------
  {id: 500, argomento: "Influenza", domanda: "Scenario clinico rapido su Influenza: quale principio terapeutico generale va applicato?", risposta: "Identificare gravità, indicazione specifica, controindicazioni e scegliere farmaco/dose coerenti con la dispensa."},
];

export const argomenti = [...new Set(domande.map(d => d.argomento))];
export default domande;
